// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    _id_52BD();
    thread initloot();
}

_id_52BD()
{
    level.spy_fx["weapon_pickup_red"] = loadfx( "vfx/test/br/weapon_pickup_red" );
    level.spy_fx["weapon_pickup_orange"] = loadfx( "vfx/test/br/weapon_pickup_orange" );
    level.spy_fx["weapon_pickup_yellow"] = loadfx( "vfx/test/br/weapon_pickup_yellow" );
    level.spy_fx["weapon_pickup_green"] = loadfx( "vfx/test/br/weapon_pickup_green" );
    level.spy_fx["weapon_pickup_blue"] = loadfx( "vfx/test/br/weapon_pickup_blue" );
}

initloot()
{
    level.spyloot = [];
    level.spyloot[0] = [];
    level.spyloot[1] = [];
    level.spylootchancetotal = [];
    level.spylootchancetotal[0] = 0.0;
    level.spylootchancetotal[1] = 0.0;
    addlootweapon( "m1941_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.5, 0.5, 0.5, 0 );
    addlootweapon( "stg44_mp", 2.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.5, 0.5, 0.5, 0 );
    addlootweapon( "fg42_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.5, 0.5, 0.5, 0 );
    addlootweapon( "bar_mp", 2.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.5, 0.5, 0.5, 0 );
    addlootweapon( "svt40_mp", 4.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 1 );
    addlootweapon( "m1a1_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 1 );
    addlootweapon( "m1garand_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 1 );
    addlootweapon( "greasegun_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 2 );
    addlootweapon( "ppsh41_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 2 );
    addlootweapon( "type100_mp", 1.5, 1, ( 3, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 2 );
    addlootweapon( "mp28_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 2 );
    addlootweapon( "thompson_mp", 0.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 2 );
    addlootweapon( "mp40_mp", 1.5, 1, ( 3, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 2 );
    addlootweapon( "lewis_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.5, 0.5, 3 );
    addlootweapon( "mg15_mp", 2.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.5, 0.5, 0.5, 3 );
    addlootweapon( "bren_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.5, 0.5, 3 );
    addlootweapon( "mg42_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.5, 0.5, 3 );
    addlootweapon( "karabin_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 4 );
    addlootweapon( "leeenfield_mp", 2.5, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 4 );
    addlootweapon( "springfield_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 4 );
    addlootweapon( "kar98_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 4 );
    addlootweapon( "winchester1897_mp", 1.5, 1, ( 3, 0, 0 ), ( 0, 0, 0 ), "orange", 0.5, 0.5, 0.5, 5 );
    addlootweapon( "m30_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 5 );
    addlootweapon( "walther_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.5, 0.5, 5 );
    addlootweapon( "model21_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.5, 5 );
    addlootweapon( "luger_mp", 3.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 2.5, 0.5, 0.0, 6 );
    addlootweapon( "m1911_mp", 0.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.0, 6 );
    addlootweapon( "m712_mp", 3.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.5, 0.0, 6 );
    addlootweapon( "panzerschreck_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.0, 0.0, 7 );
    addlootweapon( "bazooka_mp", 1.0, 1, ( 12, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.0, 0.0, 7 );
    waittillframeend;
    initlootlocations();
    level.spylootlocations[0] = common_scripts\utility::array_randomize( level.spylootlocations[0] );
    var_0 = int( level.spylootlocations[0].size * lootdensity() );

    if ( var_0 > lootmaxspawneditems() )
        var_0 = lootmaxspawneditems();

    for ( var_1 = 0; var_1 < var_0; var_1++ )
    {
        if ( var_1 < level.spylootlocations[1].size )
        {
            var_2 = 1;
            var_3 = level.spylootlocations[1][var_1];
        }
        else
        {
            var_2 = 0;
            var_3 = level.spylootlocations[2][var_1];
        }

        var_4 = randomfloatrange( 0.0, level.spylootchancetotal[var_2] );
        var_5 = undefined;

        foreach ( var_7 in level.spyloot[var_2] )
        {
            if ( var_4 >= var_7.chancerangestart[var_2] && var_4 < var_7.chancerangeend[var_2] )
            {
                var_5 = var_7;
                break;
            }
        }

        if ( !isdefined( var_5 ) )
        {

        }

        spawnloot( var_5, var_3 );
    }
}

addlootcommon( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    if ( isdefined( level.spyloot[0][var_0] ) )
        return;

    var_6 = spawnstruct();
    var_6.name = var_0;
    var_6.originoffset = var_3;
    var_6.anglesoffset = var_4;
    var_6._id_3F74 = var_5;
    var_6.loottype = 0;
    var_6.chancerangestart = [];
    var_6.chancerangeend = [];
    var_7 = [];
    var_7[0] = var_1;
    var_7[1] = common_scripts\utility::_id_98E7( var_2, var_1, 0.0 );

    for ( var_8 = 0; var_8 < 2; var_8++ )
    {
        var_6.chancerangestart[var_8] = level.spylootchancetotal[var_8];
        level.spylootchancetotal[var_8] = level.spylootchancetotal[var_8] + var_7[var_8];
        var_6.chancerangeend[var_8] = level.spylootchancetotal[var_8];
        level.spyloot[var_8][var_0] = var_6;
    }

    return var_6;
}

addlootweapon( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    var_10 = addlootcommon( var_0, var_1, var_2, var_3, var_4, var_5 );
    var_10.loottype = 1;
    var_10.startclips = var_6;
    var_10.attachment1chance = var_7;
    var_10.attachment2chance = var_8;
    var_10.weapontypeenum = var_9;
}

addlootpickup( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    var_9 = addlootcommon( var_0, var_1, var_2, var_3, var_4, var_5 );
    var_9.loottype = 2;
    var_9.model = var_6;
    var_9._id_00C5 = var_7;
    var_9.onpickupfunc = var_8;
}

initlootlocations()
{
    level.spylootlocations = [];

    for ( var_0 = 0; var_0 < 3; var_0++ )
        level.spylootlocations[var_0] = [];

    addpathnodelootlocations();
    addhardcodedlootlocations();
    var_1 = common_scripts\utility::_id_46B7( "spy_loot_location", "targetname" );
    common_scripts\utility::_id_0FB2( var_1, ::lootlocationinit, 0 );
    var_1 = common_scripts\utility::_id_46B7( "spy_loot_location_force_use", "targetname" );
    common_scripts\utility::_id_0FB2( var_1, ::lootlocationinit, 1 );
}

lootlocationinit( var_0 )
{
    self.origin = self.origin + ( 0, 0, lootgroundoffset() );
    self.forceuse = var_0;
    level.spylootlocations[0][level.spylootlocations[0].size] = self;

    if ( var_0 )
        level.spylootlocations[1][level.spylootlocations[1].size] = self;
    else
        level.spylootlocations[2][level.spylootlocations[2].size] = self;
}

addpathnodelootlocations()
{
    var_0 = 2;
    var_1 = 25;
    var_2 = lootpathnodesoutside();
    var_3 = lootpathnodesinsideparial();
    var_4 = lootpathnodesinsidecomplete();
    level.spyinteriors = [];
    var_5 = getallnodes();
    var_5 = common_scripts\utility::array_randomize( var_5 );

    foreach ( var_7 in var_5 )
    {
        if ( var_7.type != "Path" )
            continue;

        updateinteriorlocations( var_7 );
    }

    var_9 = [];

    foreach ( var_12, var_11 in level.spyinteriors )
        var_9[var_12] = level.spyinteriors[var_12].size;

    foreach ( var_7 in var_5 )
    {
        var_14 = 0;

        if ( common_scripts\utility::_id_562E( var_7.noloot ) )
            continue;

        if ( var_7.type != "Path" )
            continue;

        if ( _func_200( var_7, 1 ) )
        {
            if ( randomfloat( 1.0 ) > var_2 )
                continue;
        }
        else if ( _func_200( var_7, 0 ) )
        {
            if ( randomfloat( 1.0 ) > var_3 )
                continue;
        }
        else
        {
            if ( isdefined( var_7.interiorindex ) )
            {
                if ( level.spyinteriors[var_7.interiorindex].size <= var_0 )
                    continue;

                if ( var_9[var_7.interiorindex] > 0 )
                {
                    var_9[var_7.interiorindex] = var_9[var_7.interiorindex] - var_1;
                    var_14 = 1;
                }
            }

            if ( !var_14 && randomfloat( 1.0 ) > var_4 )
                continue;
        }

        var_15 = ( 0, randomfloatrange( 0, 360 ), 0 );
        var_16 = addlootlocation( var_7.origin, var_15, var_14 );
        var_16._id_010D = var_7;
        setnolootonconenctednodes( var_7, var_7, 0, lootpathnodesmindist() );
    }
}

addhardcodedlootlocations()
{
    switch ( level._id_015D )
    {
        case "mp_gibraltar_02":
            break;
        default:
            break;
    }
}

lootlocationcreate( var_0, var_1, var_2 )
{
    var_3 = spawnstruct();
    var_3.origin = var_0;
    var_3.angles = var_1;

    if ( common_scripts\utility::_id_562E( var_2 ) )
        var_3.targetname = "spy_loot_location_force_use";
    else
        var_3.targetname = "spy_loot_location";

    return var_3;
}

addlootlocation( var_0, var_1, var_2 )
{
    var_3 = lootlocationcreate( var_0, var_1, var_2 );
    common_scripts\utility::_id_096C( var_3 );
    return var_3;
}

nodeneedsinteriorindex( var_0 )
{
    return !isdefined( var_0.interiorindex ) && !_func_200( var_0, 0 );
}

updateinteriorlocations( var_0 )
{
    if ( !nodeneedsinteriorindex( var_0 ) )
        return;

    var_1 = level.spyinteriors.size;
    level.spyinteriors[var_1] = [];
    var_0.interiorindex = var_1;
    level.spyinteriors[var_1][0] = var_0;

    for ( var_2 = 0; var_2 < level.spyinteriors[var_1].size; var_2++ )
    {
        var_3 = level.spyinteriors[var_1][var_2];
        var_4 = _func_204( var_3 );

        foreach ( var_6 in var_4 )
        {
            if ( nodeneedsinteriorindex( var_6 ) )
            {
                var_6.interiorindex = var_1;
                var_7 = level.spyinteriors[var_1].size;
                level.spyinteriors[var_1][var_7] = var_6;
            }
        }
    }
}

setnolootonconenctednodes( var_0, var_1, var_2, var_3 )
{
    var_1.loopcheck = var_0;
    var_4 = _func_204( var_1 );

    foreach ( var_6 in var_4 )
    {
        if ( isdefined( var_6.loopcheck ) && var_6.loopcheck == var_0 )
            continue;

        var_7 = distance( var_1.origin, var_6.origin );

        if ( var_2 + var_7 < var_3 )
        {
            var_6.noloot = 1;

            if ( !isdefined( var_0.nolootnodes ) )
                var_0.nolootnodes = [];

            var_0.nolootnodes[var_0.nolootnodes.size] = var_6;
            setnolootonconenctednodes( var_0, var_6, var_2 + var_7, var_3 );
        }
    }
}

spawnloot( var_0, var_1 )
{
    switch ( var_0.loottype )
    {
        case 1:
            spawnlootweapon( var_0, var_1 );
            break;
        case 2:
            spawnlootpickup( var_0, var_1 );
            break;
        case 0:
        default:
            break;
    }
}

spawnlootweapon( var_0, var_1 )
{
    var_2 = var_0.name;
    var_3 = _func_372( var_0.name );
    var_4 = [];

    foreach ( var_6 in var_3 )
    {
        if ( var_6.size > 2 )
        {
            var_7 = getsubstr( var_6, var_6.size - 2, var_6.size );

            if ( var_7 == "_1" || var_7 == "_2" )
                var_4[var_4.size] = var_6;
        }
    }

    foreach ( var_10 in var_4 )
        var_3 = common_scripts\utility::_id_0F93( var_3, var_10 );

    var_12 = _func_3A1( var_0.name );

    foreach ( var_15, var_14 in var_12 )
        var_3 = common_scripts\utility::_id_0F93( var_3, var_14 );

    var_16 = [ "extended_mag", "telescopic_sight" ];

    foreach ( var_18 in var_16 )
    {
        var_19 = [];

        foreach ( var_6 in var_3 )
        {
            if ( issubstr( var_6, var_18 ) )
                var_19[var_19.size] = var_6;
        }

        foreach ( var_23 in var_19 )
            var_3 = common_scripts\utility::_id_0F93( var_3, var_23 );
    }

    var_26 = undefined;
    var_27 = undefined;

    if ( randomfloat( 1.0 ) < var_0.attachment1chance && var_3.size > 0 )
    {
        var_26 = common_scripts\utility::random( var_3 );

        if ( randomfloat( 1.0 ) < var_0.attachment2chance )
        {
            var_28 = tablelookuprownum( "mp/attachmentcombos_mtx12.csv", 0, var_26 );
            var_29 = _func_27B( "mp/attachmentcombos_mtx12.csv" );

            for ( var_30 = 0; var_30 < var_29; var_30++ )
            {
                var_31 = tablelookupbyrow( "mp/attachmentcombos_mtx12.csv", var_28, var_30 );

                if ( var_31 == "no" )
                {
                    var_32 = tablelookupbyrow( "mp/attachmentcombos_mtx12.csv", 0, var_30 );
                    var_3 = common_scripts\utility::_id_0F93( var_3, var_32 );
                }
            }

            if ( var_3.size > 0 )
                var_27 = common_scripts\utility::random( var_3 );
        }
    }

    if ( var_0.weapontypeenum == 4 )
    {
        if ( !isdefined( var_26 ) || var_26 == "hold_breath_1" )
            var_26 = "hold_breath_3";
        else if ( var_26 != "hold_breath_3" )
            var_27 = "hold_breath_3";
    }

    if ( isdefined( var_26 ) && isdefined( var_27 ) )
    {
        if ( stricmp( var_26, var_27 ) > 0 )
        {
            var_33 = var_26;
            var_26 = var_27;
            var_27 = var_33;
        }
    }

    if ( isdefined( var_26 ) )
    {
        var_2 = var_2 + ( "+" + var_26 );

        if ( isdefined( var_27 ) )
            var_2 = var_2 + ( "+" + var_27 );
    }

    spawnweaponitem( var_2, var_0, var_1 );
}

spawnweaponitem( var_0, var_1, var_2 )
{
    var_3 = "weapon_" + var_0;
    var_4 = spawn( var_3, ( 0, 0, 0 ), lootweaponitemflags( var_0 ) );
    spawnlootinitent( var_4, var_1, var_2 );
    lootweaponsetstartammo( var_4, var_1, var_0 );
    var_4 thread _id_0513::_id_A934();
    var_4 thread lootweaponwatchpickup();
    return var_4;
}

lootweaponitemflags( var_0 )
{
    var_1 = 0;

    if ( lootdroptoground() )
        var_1 = var_1 | itemspawnflagsuspended();

    if ( weaponisakimbo( var_0 ) )
        var_1 = var_1 | itemspawnflagakimbo();

    var_1 = var_1 | itemspawnflagsprintuse();
    return var_1;
}

weaponisakimbo( var_0 )
{
    var_1 = getweaponattachments( var_0, 1 );

    foreach ( var_3 in var_1 )
    {
        if ( issubstr( var_3, "akimbo" ) )
            return 1;
    }

    return 0;
}

lootweaponsetstartammo( var_0, var_1, var_2 )
{
    var_3 = weaponclipsize( var_2 );
    var_4 = int( var_1.startclips * var_3 );

    if ( var_4 > var_3 )
    {
        var_5 = var_3;
        var_6 = var_4 - var_3;
    }
    else
    {
        var_5 = var_4;
        var_6 = 0;
    }

    if ( weaponisakimbo( var_2 ) )
        var_0 _meth_817E( var_5, var_6 * 2, var_5 );
    else
        var_0 _meth_817E( var_5, var_6 );

    var_0 _meth_86B3( 0 );
}

spawnlootpickup( var_0, var_1 )
{
    var_2 = spawn( "script_model", ( 0, 0, 0 ), lootpickupscriptmoverflags() );
    var_2 setmodel( var_0.model );
    var_2.onpickupfunc = var_0.onpickupfunc;
    spawnlootinitent( var_2, var_0, var_1 );
    var_2 makeusable();
    var_2 _meth_80CE( var_0._id_00C5 );
    var_2 thread pickuponused();
}

spawnlootinitent( var_0, var_1, var_2 )
{
    var_3 = rotatevector( var_1.originoffset, var_2.angles );
    var_0.origin = var_2.origin + var_3;
    var_0.angles = var_2.angles + var_1.anglesoffset;
    var_0.targetname = "spy_loot";
    var_0.loottype = var_1.loottype;
    var_0.lootname = var_1.name;
    var_0._id_3F77 = var_2.origin;
    thread spawnlootfx( var_0, var_1._id_3F74 );
}

lootpickupscriptmoverflags()
{
    return scriptmoverspawnflagsprintuse();
}

pickuponused()
{
    self endon( "death" );

    for (;;)
    {
        self waittill( "trigger", var_0 );

        if ( !maps\mp\_utility::isreallyalive( var_0 ) )
            continue;

        self [[ self.onpickupfunc ]]( self.lootname, var_0 );
        break;
    }

    waittillframeend;
    self delete();
}

lootweaponwatchpickup()
{
    self endon( "death" );
    var_0 = _id_0513::_id_452C();

    for (;;)
    {
        self waittill( "trigger", var_1, var_2, var_3, var_4, var_5 );

        if ( !isdefined( var_3 ) || !isdefined( var_4 ) )
            continue;

        if ( var_3 == var_4 )
        {
            if ( var_3 )
                return;
        }
        else
            break;
    }

    if ( isdefined( var_0 ) && var_0 == var_1.primaryweapon )
        return;

    if ( isdefined( var_0 ) && var_0 == var_1._id_835A )
        return;

    var_6 = 0;
    var_7 = var_1 getweaponlistprimaries();

    foreach ( var_9 in var_7 )
    {
        if ( isdefined( var_9 ) && var_9 == "shovel_mp" )
        {
            var_6 = 1;
            break;
        }
    }

    if ( var_6 )
    {
        if ( isdefined( var_2 ) )
        {
            var_1 takeweapon( "shovel_mp" );
            _id_0513::updateplayervariablesforweaponexchange( var_1, "shovel_mp", var_0 );
            var_11 = var_2 _id_0513::_id_452C();
            var_1 giveweapon( var_11 );
            var_12 = var_2 _meth_85F2();
            var_1 setweaponammoclip( var_11, var_12["clip_ammo"] );
            var_1 setweaponammostock( var_11, var_12["stock_ammo"] );
            var_2 delete();
        }
        else
        {
            var_13 = var_1.currentweapon;

            if ( shouldrestoreweapontoplayer( var_13, var_1 ) )
            {
                var_1 takeweapon( "shovel_mp" );
                _id_0513::updateplayervariablesforweaponexchange( var_1, "shovel_mp", var_0 );
                var_1 giveweapon( var_13 );
                var_1 setweaponammoclip( var_13, 0 );
                var_1 setweaponammostock( var_13, 0 );
            }
        }
    }
    else if ( isdefined( var_2 ) )
    {
        var_11 = var_2 _id_0513::_id_452C();
        var_14 = var_1 dropweaponbattleroyale( var_11 );
        var_15 = var_2 _meth_85F2();
        var_16 = var_15["clip_ammo"];
        var_17 = var_15["stock_ammo"];
        var_18 = var_15["clip_ammo_left"];

        if ( !isdefined( var_18 ) )
            var_18 = 0;

        var_14 _meth_817E( var_16, var_17, var_18 );
        _id_0513::updateplayervariablesforweaponexchange( var_1, var_11, var_0 );
        var_2 delete();
    }
}

shouldrestoreweapontoplayer( var_0, var_1 )
{
    if ( !isdefined( var_0 ) )
        return 0;

    if ( var_0 == "shovel_mp" )
        return 0;

    if ( var_1 _meth_8319( var_0 ) )
        return 0;

    var_2 = maps\mp\_utility::_id_4431( var_0 );

    if ( !isdefined( level.spyloot[0][var_2] ) )
        return 0;

    if ( level.spyloot[0][var_2].loottype != 1 )
        return 0;

    return 1;
}

dropweaponbattleroyale( var_0 )
{
    var_1 = maps\mp\_utility::_id_4738( var_0 );

    if ( var_1[0] == "alt" )
    {
        var_0 = var_1[1];

        for ( var_2 = 2; var_2 < var_1.size; var_2++ )
            var_0 = var_0 + "_" + var_1[var_2];
    }

    var_3 = maps\mp\_utility::_id_4431( var_0 );
    var_4 = level.spyloot[0][var_3];
    var_5 = lootgetgroundpos( self.origin );
    var_5 = var_5 + ( 0, 0, lootgroundoffset() );
    var_6 = self.angles;
    var_7 = lootlocationcreate( var_5, var_6 );
    return spawnweaponitem( var_0, var_4, var_7 );
}

spawnlootfx( var_0, var_1 )
{
    var_0 endon( "death" );

    if ( var_0.loottype == 1 )
    {
        if ( !( var_0.spawnflags & itemspawnflagsuspended() ) )
        {
            var_2 = var_0.origin + ( 0, 0, 1 );

            while ( var_2 != var_0.origin )
            {
                var_2 = var_0.origin;
                waitframe();
            }
        }
    }

    var_3 = spawnfx( level.spy_fx["weapon_pickup_" + var_1], var_0._id_3F77 );
    triggerfx( var_3 );
    var_0 waittill( "trigger" );
    var_3 delete();
}

lootdropweapon( var_0 )
{
    var_1 = maps\mp\_utility::_id_4738( var_0 );

    if ( var_1[0] == "alt" )
    {
        var_0 = var_1[1];

        for ( var_2 = 2; var_2 < var_1.size; var_2++ )
            var_0 = var_0 + "_" + var_1[var_2];
    }

    var_3 = maps\mp\_utility::_id_4431( var_0 );
    var_4 = level.brloot[0][var_3];
    var_5 = lootgetgroundpos( self.origin );
    var_5 = var_5 + ( 0, 0, lootgroundoffset() );
    var_6 = self.angles;
    var_7 = lootlocationcreate( var_5, var_6 );
    return spawnweaponitem( var_0, var_4, var_7 );
}

weaponenumtostring( var_0 )
{
    switch ( var_0 )
    {
        case 0:
            return "AR";
        case 1:
            return "AR Semi";
        case 2:
            return "SMG";
        case 3:
            return "LMG";
        case 4:
            return "Sniper";
        case 5:
            return "Shotgun";
        case 6:
            return "Pistol";
        case 7:
            return "Launcher";
        case 8:
            return "Melee";
        default:
            return "Unknown";
    }
}

lootdensity()
{
    return getdvarfloat( "scr_spy_loot_density", 0.6 );
}

lootdroptoground()
{
    return getdvarint( "scr_spy_loot_drop_to_ground", 1 );
}

lootgroundoffset()
{
    return getdvarfloat( "scr_spy_loot_ground_offset", 30 );
}

lootmaxspawneditems()
{
    return 100;
}

lootpathnodesoutside()
{
    return getdvarfloat( "scr_spy_loot_path_nodes_outside", 0.02 );
}

lootpathnodesinsideparial()
{
    return getdvarfloat( "scr_spy_loot_path_nodes_inside_partial", 0.0 );
}

lootpathnodesinsidecomplete()
{
    return getdvarfloat( "scr_spy_loot_path_nodes_inside_complete", 1.0 );
}

lootpathnodesmindist()
{
    return getdvarint( "scr_spy_loot_path_nodes_min_dist", 220 );
}

lootgetgroundpos( var_0 )
{
    return bullettrace( var_0 + ( 0, 0, 10 ), var_0 + ( 0, 0, -1000 ), 0, self, 0, 0, 0, 0, 1, 1, 0 )["position"];
}

itemspawnflagsuspended()
{
    return 1;
}

itemspawnflagakimbo()
{
    return 4;
}

itemspawnflagsprintuse()
{
    return 16;
}

scriptmoverspawnflagsprintuse()
{
    return 16;
}
