// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

spyclasstostring( var_0 )
{
    if ( !isdefined( var_0 ) )
        return "<undefined>";

    switch ( var_0 )
    {
        case 0:
            return "civilian";
        case 1:
            return "detective";
        case 2:
            return "traitor";
        case 16777215:
            return "none";
        default:
            return "unknown";
    }
}

spyclasstolocstring( var_0 )
{
    if ( !isdefined( var_0 ) )
        return "<undefined>";

    switch ( var_0 )
    {
        case 0:
            return &"MP_SPY_CLASS_CIVILIAN";
        case 1:
            return &"MP_SPY_DETECTIVE";
        case 2:
            return &"MP_SPY_CLASS_TRAITOR";
        case 16777215:
            return "none";
        default:
            return "unknown";
    }
}

spyclassfriendlycheck( var_0, var_1 )
{
    if ( var_0 == 0 || var_0 == 1 )
        return var_1 == 0 || var_1 == 1;
    else
        return var_1 == 2;
}
