// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    _id_04D4::init();
    maps\mp\gametypes\_callbacksetup::setupcallbacks();
    _id_04D4::setupcallbacks();

    if ( isusingmatchrulesdata() )
    {
        level._id_5300 = ::_id_5300;
        [[ level._id_5300 ]]();
        level thread maps\mp\_utility::_id_7C13();
    }
    else
    {
        maps\mp\_utility::registertimelimitdvar( level.gametype, 0 );
        maps\mp\_utility::registerscorelimitdvar( level.gametype, 1 );
        maps\mp\_utility::registerroundlimitdvar( level.gametype, 0 );
        maps\mp\_utility::registerwinlimitdvar( level.gametype, 3 );
        maps\mp\_utility::registernumlivesdvar( level.gametype, 1 );
        maps\mp\_utility::registerhalftimedvar( level.gametype, 0 );
        level._id_6031 = 0;
        level._id_6035 = 0;
    }

    level._id_5A74 = 1;
    level._id_5A6F = 0;
    level.disabledivisionstats = 1;
    level.disabledivisionpassives = 1;
    level.disabledivisionskills = 1;
    level.firstplayerspawned = 0;
    level.mgnestsdisabled = 1;
    level.partners = 0;
    level._id_6BA7 = ::_id_6BA7;
    level._id_6B7B = ::_id_6B7B;
    level._id_6BAF = ::_id_6BAF;
    level._id_6B5C = ::_id_6B5C;
    level._id_6B7F = ::_id_6B7F;
    level._id_62AD = ::modifyplayerdamagebattleroyale;
    level._id_3FC7 = ::maydropweaponbattleroyale;
    level._id_3FDD = ::applybattleroyaleperks;
    setdynamicdvar( "scr_player_healthregentime", 0 );
    setdynamicdvar( "1605", maxspawnedlootitems() );
    setdvarifuninitialized( "scr_br_loot_density", 0.6 );
    setdvarifuninitialized( "scr_br_loot_drop_to_ground", 1 );
    setdvarifuninitialized( "scr_br_loot_ground_offset", 10 );
    setdvarifuninitialized( "scr_br_loot_path_nodes_outside", 0.02 );
    setdvarifuninitialized( "scr_br_loot_path_nodes_inside_partial", 0.0 );
    setdvarifuninitialized( "scr_br_loot_path_nodes_inside_complete", 1.0 );
    setdvarifuninitialized( "scr_br_loot_path_nodes_min_dist", 100 );
    setdvarifuninitialized( "scr_br_insertion_delay", 3.0 );

    if ( level._id_6031 || level._id_6035 )
        level._id_62AD = maps\mp\gametypes\_damage::_id_3FC8;

    setteammode( "ffa" );
    level.objectivebased = 1;
    maps\mp\_utility::_id_873B( 0 );
    game["dialog"]["gametype"] = "br_intro";
    game["dialog"]["defense_obj"] = "gbl_start";
    game["dialog"]["offense_obj"] = "gbl_start";

    if ( getdvarint( "2043" ) )
        game["dialog"]["gametype"] = "hc_" + game["dialog"]["gametype"];

    level.br_fx["weapon_pickup_red"] = loadfx( "vfx/test/br/weapon_pickup_red" );
    level.br_fx["weapon_pickup_orange"] = loadfx( "vfx/test/br/weapon_pickup_orange" );
    level.br_fx["weapon_pickup_yellow"] = loadfx( "vfx/test/br/weapon_pickup_yellow" );
    level.br_fx["weapon_pickup_green"] = loadfx( "vfx/test/br/weapon_pickup_green" );
    level.br_fx["weapon_pickup_blue"] = loadfx( "vfx/test/br/weapon_pickup_blue" );
    thread initloot();
}

_id_5300()
{
    maps\mp\_utility::_id_8653( 1 );
    var_0 = getmatchrulesdata( "commonOption", "scoreLimit" );
    setdynamicdvar( "scr_br_winlimit", var_0 );
    maps\mp\_utility::registerwinlimitdvar( "br", var_0 );
    setdynamicdvar( "scr_br_roundlimit", 0 );
    maps\mp\_utility::registerroundlimitdvar( "br", 0 );
    setdynamicdvar( "scr_br_scorelimit", 0 );
    maps\mp\_utility::registerscorelimitdvar( "br", 1 );
    setdynamicdvar( "scr_br_halftime", 0 );
    maps\mp\_utility::registerhalftimedvar( "br", 0 );
    setdynamicdvar( "scr_br_numlives", 1 );
    maps\mp\_utility::registernumlivesdvar( "br", 1 );
}

_id_6BAF()
{
    setclientnamemode( "auto_change" );
    maps\mp\_utility::setobjectivetext( "allies", &"OBJECTIVES_BR" );
    maps\mp\_utility::setobjectivetext( "axis", &"OBJECTIVES_BR" );

    if ( level.splitscreen )
    {
        maps\mp\_utility::setobjectivescoretext( "allies", &"OBJECTIVES_BR" );
        maps\mp\_utility::setobjectivescoretext( "axis", &"OBJECTIVES_BR" );
    }
    else
    {
        maps\mp\_utility::setobjectivescoretext( "allies", &"OBJECTIVES_BR_SCORE" );
        maps\mp\_utility::setobjectivescoretext( "axis", &"OBJECTIVES_BR_SCORE" );
    }

    maps\mp\_utility::setobjectivehinttext( "allies", &"OBJECTIVES_BR_HINT" );
    maps\mp\_utility::setobjectivehinttext( "axis", &"OBJECTIVES_BR_HINT" );
    _id_050D::_id_10E4();
    level._id_A239 = 1;
    var_0[0] = "br";
    _id_04D1::main( var_0 );
    level._id_7895 = 1;
    level.claimednodes = [];
    maps\mp\_utility::gameflaginit( "players_deployed", 0 );
    level thread onplayerconnect();
    level thread waittospawnplayers();
    level thread runshrinkingcircle();
}

onplayerconnect()
{
    level endon( "game_ended" );

    for (;;)
    {
        level waittill( "connected", var_0 );
        var_0._id_3C6F = 1;
        var_0._id_7682 = ::playerprekillbattleroyale;

        if ( !isbot( var_0 ) )
        {
            if ( level._id_258F )
                var_0 _meth_82E1( "tryUseMedkit", "+actionslot 4" );
            else
                var_0 _meth_82E1( "tryUseMedkit", "+actionslot 5" );
        }

        var_0 thread playerhideteamchoiceonselect();
        setdvar( "1979", 0 );
        level thread onplayerspawned( var_0 );
    }
}

_id_6BA7()
{
    setplayerclass( self );
}

setplayerclass( var_0 )
{
    var_1 = maps\mp\gametypes\_class::_id_44B4();
    var_1["loadoutDivision"] = randomint( 5 );
    var_1["loadoutPrimaryWeaponStruct"] = maps\mp\_utility::_id_473C( 17113088, 0 );
    var_0.pers["class"] = "gamemode";
    var_0.pers["lastClass"] = "";
    var_0.pers["gamemodeLoadout"] = var_1;
    var_0.class = var_0.pers["class"];
    var_0.lastclass = var_0.pers["lastClass"];
    var_0 maps\mp\gametypes\_class::_id_4790( var_0.team, var_0.class );
}

onplayerspawned( var_0 )
{
    level endon( "game_ended" );
    var_0 endon( "disconnect" );

    for (;;)
    {
        var_0 waittill( "spawned_player" );
        var_0 _meth_82FF( "ui_hide_minimap", 1 );

        if ( common_scripts\utility::_id_562E( var_0._id_3C6F ) )
        {
            var_0._id_3C6F = 0;
            var_1 = getrandomspawnnodeforplayer( var_0 );
            var_0 playerclaimspawnnode( var_1 );

            if ( !maps\mp\_utility::gameflag( "prematch_done" ) )
                var_0 thread playertargetedspawn();
        }

        var_0 thread playercircleaudio();
        var_0 thread playermonitorcircle();
        var_0 playerpartnersetup();
        var_0 playermedkitinit();
        var_0 thread playermedkitusemonitor();
        var_0 thread playermedkithud();
        level.firstplayerspawned = 1;
    }
}

checkendgamepartnermodeonkill()
{
    waitframe();
    var_0 = [];

    foreach ( var_2 in level.players )
    {
        if ( var_2 maps\mp\gametypes\_playerlogic::mayspawn() )
            return;

        if ( maps\mp\_utility::isreallyalive( var_2 ) )
            var_0[var_0.size] = var_2;
    }

    if ( var_0.size == 2 && isdefined( var_0[0].partner ) && var_0[0].partner == var_0[1] )
        level thread maps\mp\gametypes\_gamelogic::_id_36B9( var_0[0], game["end_reason"]["enemies_eliminated"] );
}

_id_6B7B( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    if ( common_scripts\utility::_id_562E( level.partners ) )
        level thread checkendgamepartnermodeonkill();

    var_10 = [];

    if ( self.nummedkits > 0 )
        var_10[var_10.size] = "medkit";

    level thread playdeathstingersforteams( self );

    if ( isdefined( self.victimcurrentlethal ) && self.victimcurrentlethal != "none" && self.victimcurrentlethal != "" )
        var_10[var_10.size] = self.victimcurrentlethal;

    if ( isdefined( self.victimcurrenttactical ) && self.victimcurrenttactical != "none" && self.victimcurrenttactical != "" )
        var_10[var_10.size] = self.victimcurrenttactical;

    if ( var_10.size > 0 )
    {
        var_11 = 40;
        var_12 = 10;
        var_13 = lootgetgroundpos( self.origin );
        var_14 = randomfloatrange( 0, 360 );
        var_15 = [];

        foreach ( var_26, var_17 in var_10 )
        {
            var_18 = anglestoforward( ( 0, var_14 + var_26 / var_10.size * 360.0, 0 ) );
            var_19 = var_13 + ( 0, 0, 50 );
            var_20 = var_11 + var_12;
            var_21 = var_19 + var_18 * var_20;
            var_22 = bullettrace( var_19, var_21, 0, self._id_18A8 );
            var_23 = var_22["fraction"] * var_20;
            var_24 = var_23 - var_12;

            if ( var_24 > 0 )
            {
                var_25 = var_19 + var_18 * var_24;
                var_25 = lootgetgroundpos( var_25 );
            }
            else
                var_25 = var_13;

            var_15[var_26] = var_25;
        }

        foreach ( var_26, var_17 in var_10 )
        {
            var_28 = level.brloot[0][var_17];
            var_29 = ( 0, randomfloatrange( 0, 360 ), 0 );
            var_30 = lootlocationcreate( var_15[var_26], var_29 );
            var_30 lootlocationinit( 0 );
            spawnloot( var_28, var_30 );
        }
    }
}

_id_6B5C( var_0, var_1, var_2 )
{
    if ( !_id_A870( var_0, var_1 ) )
        return;

    if ( var_1 == self )
        return;

    var_3 = _id_5742( var_1 );

    if ( var_3 )
        var_1._id_3B4B = 1;

    var_1 thread _id_047A::_id_35D2( var_3, var_0 );
}

_id_A870( var_0, var_1 )
{
    if ( maps\mp\gametypes\_damage::_id_56FA( var_0, var_1 ) )
        return 0;

    if ( var_0 maps\mp\gametypes\_playerlogic::mayspawn() )
        return 0;

    return 1;
}

_id_5742( var_0 )
{
    foreach ( var_2 in level.players )
    {
        if ( var_2 == var_0 )
            continue;

        if ( var_2 maps\mp\gametypes\_playerlogic::mayspawn() )
            return 0;

        if ( maps\mp\_utility::isreallyalive( var_2 ) )
            return 0;
    }

    return 1;
}

_id_6B7F( var_0, var_1, var_2, var_3, var_4 )
{
    var_5 = maps\mp\gametypes\_rank::getscoreinfovalue( var_0 );
    var_1 maps\mp\_utility::_id_867B( var_1._id_008F + var_5 );
    var_1 _id_04D2::_id_A161( var_1, var_5 );

    if ( _id_57BF( var_0 ) )
        return 1;

    return 0;
}

_id_57BF( var_0 )
{
    switch ( var_0 )
    {
        case "kill":
        case "mg_nest_kill":
            return 1;
    }

    return 0;
}

applybattleroyaleperks()
{

}

maydropweaponbattleroyale( var_0 )
{
    if ( var_0 == "shovel_mp" )
        return 0;

    dropweaponbattleroyale( var_0 );
    return 0;
}

dropweaponbattleroyale( var_0 )
{
    var_1 = maps\mp\_utility::_id_4738( var_0 );

    if ( var_1[0] == "alt" )
    {
        var_0 = var_1[1];

        for ( var_2 = 2; var_2 < var_1.size; var_2++ )
            var_0 = var_0 + "_" + var_1[var_2];
    }

    var_3 = maps\mp\_utility::_id_4431( var_0 );
    var_4 = level.brloot[0][var_3];
    var_5 = lootgetgroundpos( self.origin );
    var_5 = var_5 + ( 0, 0, lootgroundoffset() );
    var_6 = self.angles;
    var_7 = lootlocationcreate( var_5, var_6 );
    return spawnweaponitem( var_0, var_4, var_7 );
}

modifyplayerdamagebattleroyale( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    if ( !maps\mp\_utility::gameflag( "prematch_done" ) )
        return 0;

    if ( !isplayer( var_0 ) )
        return var_3;

    if ( isdefined( var_0.partner ) && isdefined( var_2 ) && var_2 == var_0.partner )
        return 0;

    if ( var_4 == "MOD_FALLING" )
        return 0;

    if ( var_4 == "MOD_IMPACT" )
        return var_3;

    if ( var_4 == "MOD_TRIGGER_HURT" )
        return var_3;

    if ( var_4 == "MOD_GRENADE_SPLASH" )
        return var_3;

    if ( issniperheadshot( var_3, var_5, var_8, var_4, var_2 ) )
        return var_3;

    if ( hasshotgunequipped( var_2 ) )
        return var_3;

    if ( maps\mp\_utility::_id_5755( var_4 ) )
    {
        var_10 = maps\mp\_utility::_id_4431( var_5 );

        if ( _id_0513::_id_5756( var_5 ) && var_10 != "shovel_mp" )
            return 50;
        else
            return 32;
    }

    return int( var_3 );
}

issniperheadshot( var_0, var_1, var_2, var_3, var_4 )
{
    if ( !maps\mp\_utility::isbulletdamage( var_3 ) )
        return 0;

    if ( !maps\mp\_utility::_id_570A( var_1, var_2, var_3, var_4 ) )
        return 0;

    if ( var_0 < 100 )
        return 0;

    return 1;
}

hasshotgunequipped( var_0 )
{
    if ( !isdefined( var_0 ) )
        return 0;

    var_1 = var_0 getcurrentweapon();

    if ( !isdefined( var_1 ) )
        return 0;

    var_2 = weaponclass( var_1 );

    if ( isdefined( var_2 ) && var_2 == "spread" )
        return 1;

    return 0;
}

getparachuteinsertiondelay()
{
    return getdvarint( "scr_br_insertion_delay" );
}

waittospawnplayers()
{
    level endon( "game_ended" );
    maps\mp\_utility::gameflagwait( "prematch_done" );
    var_0 = maps\mp\_utility::getpotentiallivingplayers();
    var_1 = common_scripts\utility::array_randomize( var_0 );

    for ( var_2 = 0; var_2 < var_1.size; var_2++ )
    {
        var_3 = var_1[var_2];

        if ( !isdefined( var_3.selectedspawnnode ) )
        {
            var_4 = getrandomspawnnodeforplayer( var_3 );
            var_3 playerclaimspawnnode( var_4 );
        }
    }

    if ( level._id_7691 > 0 )
    {
        var_5 = getparachuteinsertiondelay();

        if ( var_5 > 0 )
            wait( var_5 );
    }

    foreach ( var_3 in var_0 )
    {
        var_3.selectedspawnnode = undefined;
        var_3 notify( "start_insertion" );
    }

    foreach ( var_9 in level.claimednodes )
        var_9._id_230E = undefined;

    level.claimednodes = [];
    maps\mp\_utility::gameflagset( "players_deployed" );
}

playerhideteamchoiceonselect()
{
    self endon( "disconnect" );
    self waittill( "joined_team" );
    thread maps\mp\gametypes\_playerlogic::_id_8753( -1 );
}

playerpartnerthink()
{
    if ( !isdefined( self.partner ) )
        return;

    self endon( "disconnect" );
    self endon( "death" );
    self.partner endon( "disconnect" );

    if ( isdefined( self._id_3EDE ) )
        self._id_3EDE destroy();

    self._id_00A7 = self.partner getentitynumber();
    self.partner _meth_8427( self, 2, 1 );
    self._id_3EDE = newclienthudelem( self );
    self._id_3EDE setshader( "waypoint_escort", 1, 1 );
    self._id_3EDE _meth_80CB( 1, 1, 0 );
    self._id_3EDE _meth_80C0( self.partner );
    self._id_3EDE.hidewheninmenu = 1;
    self._id_3EDE.alpha = 1.0;
}

playerpartnerpick()
{
    foreach ( var_1 in level.players )
    {
        if ( var_1 == self )
            continue;

        if ( isdefined( var_1.partner ) )
            continue;

        return var_1;
    }

    return undefined;
}

playerpartnersetup()
{
    if ( !common_scripts\utility::_id_562E( level.partners ) )
        return;

    if ( !isdefined( self.partner ) )
    {
        var_0 = playerpartnerpick();

        if ( isdefined( var_0 ) )
        {
            self.partner = var_0;
            var_0.partner = self;
            var_0 thread playerpartnerthink();
        }
    }

    if ( isdefined( self.partner ) )
        thread playerpartnerthink();
}

playertargetedspawn()
{
    self endon( "disconnect" );

    if ( getdvarint( "scr_br_showPlayersOnMap", 1 ) )
        self setperk( "specialty_radarblip", 1, 0 );

    self _meth_85CD( "none" );
    maps\mp\_utility::freezecontrolswrapper( 1 );
    spawnselectioncreateoverlay();
    self _meth_8626( "mute_all" );
    thread playersetupparachute();
    thread playerselectspawnlocation();
    level waittill( "prematch_done" );
    self notify( "stop_location_selection" );
    thread playerparachutecountdown();
    self waittill( "start_insertion" );
    self _meth_82FF( "ui_map_location_selector", 0 );
    self _meth_8627( "mute_all" );
    thread spawnselectionremoveoverlay();
    maps\mp\_utility::freezecontrolswrapper( 0 );
    self _meth_85CD( "all" );
    self unsetperk( "specialty_radarblip", 1 );
    playerparachuteinsertion();
    self _meth_85EF( &"ui_init_round", 0 );
}

playerparachutecountdown()
{
    var_0 = getparachuteinsertiondelay();

    for ( var_1 = int( var_0 ); var_1 > 0; var_1-- )
    {
        self iprintlnbold( &"MPUI_MTX1_BR_DEPLOYING_IN_X", var_1 );
        wait 1.0;
    }

    self iprintlnbold( "" );
}

spawnselectioncreateoverlay()
{
    if ( !isplayer( self ) )
        return;

    var_0 = newclienthudelem( self );
    var_0 setshader( "black", 640, 480 );
    var_0.sort = 1;
    var_0._id_00C6 = "fullscreen";
    var_0._id_01CA = "fullscreen";
    var_0.alpha = 1;
    var_0.foreground = 0;
    self.spawnselectionoverlay = var_0;
}

spawnselectionremoveoverlay()
{
    var_0 = self.spawnselectionoverlay;

    if ( isdefined( var_0 ) )
    {
        var_0 endon( "death" );
        var_0 fadeovertime( 0.5 );
        var_0.alpha = 0;
        wait 1.0;
        var_0 destroy();
    }
}

playerselectspawnlocation()
{
    self endon( "disconnect" );
    var_0 = 2;
    var_1 = 0;
    var_2 = 0.05;

    if ( !isdefined( level._id_5FF0 ) )
        level._id_5FF0 = 1024;

    var_3 = level._id_5FF0 * var_2;
    self _meth_82FF( "ui_map_location_selector", var_0 );
    self _meth_8320( "map_artillery_selector", var_1, var_3 );
    playermonitorspawnselections();
    self _meth_8321();
}

isvalidspawnnode( var_0 )
{
    if ( !_func_200( var_0, 1 ) )
        return 0;

    var_1 = var_0.origin + ( 0, 0, 3000 );

    if ( !_func_293( var_0.origin, 15, 70, self, 0, 0, 0, var_1 ) )
        return 0;

    return 1;
}

getnodeclearanceforplayer( var_0, var_1 )
{
    if ( !isdefined( var_0._id_230E ) || var_0._id_230E == var_1 )
        return 0;

    var_2 = var_0._id_230E.team;

    if ( isdefined( var_2 ) && isdefined( var_1.team ) )
    {
        if ( var_2 == var_1.team )
            return 1024;
        else
            return 16384;
    }

    return 0;
}

nodecanbeclaimedbyplayer( var_0, var_1 )
{
    foreach ( var_3 in level.claimednodes )
    {
        var_4 = getnodeclearanceforplayer( var_3, var_1 );

        if ( _func_211( var_0.origin, var_3.origin ) < var_4 )
            return 0;
    }

    return 1;
}

getalternatespawnnode( var_0, var_1 )
{
    var_2 = 1;
    var_3 = 1024;
    var_4 = 1024;

    for ( var_5 = 0; var_5 < 10; var_5++ )
    {
        var_6 = getnodesinradiussorted( var_0.origin, var_3, var_2, 10000, "path" );

        foreach ( var_0 in var_6 )
        {
            if ( !isvalidspawnnode( var_0 ) )
                continue;

            if ( !nodecanbeclaimedbyplayer( var_0, var_1 ) )
                continue;

            return var_0;
        }

        var_2 = var_3;
        var_3 = var_3 + var_4;
    }

    return undefined;
}

getrandomspawnnodeforplayer( var_0 )
{
    var_1 = [];
    var_2 = getallnodes();

    foreach ( var_4 in var_2 )
    {
        if ( common_scripts\utility::_id_562E( var_4._id_2307 ) )
            continue;

        if ( !isvalidspawnnode( var_4 ) )
            continue;

        if ( !nodecanbeclaimedbyplayer( var_4, var_0 ) )
            continue;

        var_1[var_1.size] = var_4;
    }

    var_6 = common_scripts\utility::random( var_1 );
    return var_6;
}

playermonitorspawnselections()
{
    self endon( "stop_location_selection" );
    var_0 = undefined;

    for (;;)
    {
        if ( isdefined( var_0 ) )
        {
            self iprintlnbold( var_0 );
            var_0 = undefined;
        }

        self waittill( "confirm_location", var_1, var_2 );
        var_3 = getgroundposition( var_1, 15, 0, 30000 );

        if ( !isdefined( var_3 ) )
        {
            var_0 = &"MPUI_MTX1_BR_SPAWN_ERROR_GROUND";
            continue;
        }

        var_4 = getnodesinradiussorted( var_3, 128, 0, 10000, "path" );

        if ( var_4.size < 1 )
        {
            var_0 = &"MPUI_MTX1_BR_SPAWN_ERROR_PATH";
            continue;
        }

        var_5 = undefined;

        for ( var_6 = 0; var_6 < var_4.size; var_6++ )
        {
            var_7 = var_4[var_6];

            if ( !isvalidspawnnode( var_7 ) )
            {
                var_0 = &"MPUI_MTX1_BR_SPAWN_ERROR_SKY";
                continue;
            }

            var_5 = var_7;
            break;
        }

        if ( isdefined( var_5 ) )
        {
            var_0 = undefined;

            if ( !nodecanbeclaimedbyplayer( var_5, self ) )
            {
                var_0 = &"MPUI_MTX1_BR_SPAWN_ERROR_PROXIMITY";
                continue;
            }

            playerclaimspawnnode( var_5 );
        }
    }
}

playerunclaimcurrentnode()
{
    if ( isdefined( self.selectedspawnnode ) )
    {
        self.selectedspawnnode._id_230E = undefined;
        level.claimednodes = common_scripts\utility::_id_0F93( level.claimednodes, self.selectedspawnnode );
        self.selectedspawnnode = undefined;
    }
}

playerclaimspawnnode( var_0 )
{
    playerunclaimcurrentnode();
    self.selectedspawnnode = var_0;
    var_0._id_230E = self;
    level.claimednodes[level.claimednodes.size] = var_0;
    self setorigin( var_0.origin, 1 );
    var_1 = level._id_5FEB - var_0.origin;
    self _meth_833E( ( 0, vectortoyaw( var_1 ), 0 ) );
}

playersetupparachute()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    wait 0.5;
    self _meth_8326();
    self _meth_812A( 0 );

    if ( !isbot( self ) )
    {
        self giveweapon( "br_parachute_mp" );
        self _meth_831B( "br_parachute_mp" );
    }
    else
        self _meth_8322();
}

playerteardownparachute()
{
    self _meth_812A( 1 );

    if ( !isbot( self ) )
        thread playerswitchtodefaultweapon();
    else
        self _meth_8323();
}

playerswitchtodefaultweapon()
{
    level endon( "game_ended" );
    self endon( "death" );
    self endon( "disconnect" );
    self switchtoweapon( "shovel_mp" );
    wait 1.0;
    self takeweapon( "br_parachute_mp" );
    self _meth_8327();
}

playerparachuteinsertion()
{
    self endon( "disconnect" );
    var_0 = self.origin;
    var_1 = var_0 + ( 0, 0, 3000 );
    var_2 = spawn( "script_model", var_1 );
    var_2 setmodel( "tag_origin" );
    var_2.origin = var_1;
    var_2.angles = self.angles;
    var_2 _meth_808C();
    var_3 = var_2 gettagorigin( "tag_origin" );
    self setorigin( var_3 );
    self _meth_8077( var_2, "tag_origin", 0, 180, 180, 0, 60, 0 );
    self _meth_808C();
    var_4 = spawn( "script_model", var_2.origin );
    var_4 setmodel( "usa_human_parachute" );
    var_4._id_62A0 = 0.5;
    var_4.origin = self.origin;
    var_4.angles = self.angles;
    var_4 linkto( self, "tag_origin", ( 0, 3, 20 ), ( 0, 90, 0 ) );
    var_4 _meth_808C();
    waitframe();
    thread playerparachutedrop( var_0[2] );
    thread playerparachutecleanup( var_4, var_2 );
    self _meth_800B();
    var_2 _meth_82B1( var_0, 7.0 );
}

playerparachutedrop( var_0 )
{
    level endon( "game_ended" );
    self endon( "death" );
    self endon( "disconnect" );

    for (;;)
    {
        if ( self.origin[2] < var_0 + 100 )
            break;

        wait 0.1;
    }

    self notify( "parachute_detach" );
}

playerparachutecleanup( var_0, var_1 )
{
    level endon( "game_ended" );
    common_scripts\utility::_id_A70A( "disconnect", "death", "parachute_detach" );

    if ( isdefined( self ) && isalive( self ) )
    {
        self _meth_8009( 0 );
        self _meth_8057();
        playerteardownparachute();
    }

    var_0 _meth_8278( "human_parachute_detach_d", "finished_parachute_detach" );
    var_0 _meth_8450( 1, 1, 0 );
    var_0 setmodel( "usa_human_parachute_fade" );
    var_2 = 1;
    var_0 _meth_8450( 1, 0, var_2 );
    var_0 common_scripts\utility::_id_2CBE( 1.25, ::delete );
    var_1 common_scripts\utility::_id_2CBE( 3, ::delete );
}

runshrinkingcircle()
{
    level.circleobjective = initshrinkingcircle();
    level.circleobjective circlepauseatradius( level.circleobjective._id_78CA );

    if ( level._id_7691 > 0 )
        maps\mp\_utility::gameflagwait( "players_deployed" );
    else
    {
        while ( !level.firstplayerspawned )
            waitframe();
    }

    wait 7.0;
    wait 5.0;
    level.circleobjective thread movecircle();
}

initshrinkingcircle()
{
    precachempanim( "mp_br_pubg_circle_shrink" );
    var_0 = spawnstruct();
    var_0 = initstartlocation( var_0 );
    var_0 = circleobjectivebuildpath( var_0 );
    var_0.centerent = spawn( "script_model", var_0._id_6EB7[0] );
    var_0.centerent setmodel( "tag_origin" );
    var_0.visualents = [];

    for ( var_1 = 0; var_1 <= 3; var_1++ )
    {
        var_0.visualents[var_1] = spawn( "script_model", var_0._id_9255 );
        var_0.visualents[var_1] setmodel( "br_dome_barrier_01" );
        var_0.visualents[var_1].angles = ( 0, var_1 * 90, 0 );
        var_0.visualents[var_1] linkto( var_0.centerent );
    }

    var_2 = var_0.visualents[0] gettagorigin( "tag_circle_01" );
    var_0.radiusent = spawn( "script_model", var_2 );
    var_0.radiusent setmodel( "tag_origin" );
    var_0.radiusent linkto( var_0.visualents[0], "tag_circle_01" );
    setomnvar( "ui_br_circle_ent", var_0.visualents[0] getentitynumber() );
    var_0._id_08BE = 0;
    return var_0;
}

initstartlocation( var_0 )
{
    level.brlevelmins = ( 99999, 99999, 99999 );
    level.brlevelmaxs = ( -99999, -99999, -99999 );
    var_1 = 10;
    var_2 = 15;
    var_3 = getallnodes();

    foreach ( var_5 in var_3 )
    {
        level.brlevelmins = _id_050D::_id_3915( level.brlevelmins, var_5.origin );
        level.brlevelmaxs = _id_050D::_id_3914( level.brlevelmaxs, var_5.origin );
    }

    var_7 = ( level.brlevelmaxs + level.brlevelmins ) / 2.0;
    var_8 = 0;

    foreach ( var_5 in var_3 )
    {
        var_10 = distance2d( var_7, var_5.origin );

        if ( var_10 > var_8 )
            var_8 = var_10;
    }

    var_12 = var_8;
    var_13 = getnodesinradiussorted( var_7, 512, 0 );

    if ( var_13.size )
    {
        var_0.start_node = var_13[0];
        var_7 = ( var_0.start_node.origin[0], var_0.start_node.origin[1], var_7[2] );
        var_14 = distance2d( var_0.start_node.origin, var_7 );
        var_12 = var_12 + var_14;
    }

    if ( var_12 > 9980.87 )
    {
        var_12 = 9980.87;
        var_15 = 9980.87;
    }

    var_16 = 400;

    if ( var_16 < 94.2168 )
        var_16 = 94.2168;

    var_0.touching = [];
    var_0._id_9255 = var_7;
    var_0._id_78CA = var_12;
    var_0.radius_end = var_16;
    var_0.radius_speed = var_1;
    var_0.move_speed = var_2;
    var_0.move_time = ( var_0._id_78CA - var_0.radius_end ) / var_0.radius_speed;
    return var_0;
}

circleobjectivebuildpath( var_0 )
{
    var_0._id_6EB7 = [];

    if ( isdefined( var_0.start_node ) )
    {
        var_1 = getallnodes();
        var_0._id_6EB7[0] = var_0.start_node.origin;
        var_2 = var_0.start_node;
        var_3 = var_0.move_time * var_0.move_speed;
        var_4 = 0;

        while ( !var_4 )
        {
            for (;;)
            {
                var_5 = var_1[randomint( var_1.size )];
                var_6 = getnodesonpath( var_2.origin, var_5.origin, 1, var_2, var_5 );

                if ( isdefined( var_6 ) )
                    break;
            }

            for ( var_7 = 1; var_7 < var_6.size; var_7++ )
            {
                var_8 = distance2d( var_2.origin, var_6[var_7].origin );

                if ( var_8 < var_3 )
                {
                    var_3 = var_3 - var_8;
                    var_0._id_6EB7[var_0._id_6EB7.size] = ( var_6[var_7].origin[0], var_6[var_7].origin[1], var_0._id_6EB7[0][2] );
                    var_2 = var_6[var_7];
                    continue;
                }

                var_4 = 1;
                break;
            }
        }
    }
    else
        var_0._id_6EB7[0] = var_0._id_9255 + ( 0, 0, 64 );

    return var_0;
}

circlepauseatradius( var_0 )
{
    var_1 = circleanimstartoffset( var_0 );
    circleplayanim( var_1, 1.0 );
    circlepauseanim();
}

circleanimstartoffset( var_0 )
{
    var_1 = 164.778;
    var_2 = ( 9980.87 - var_0 ) / var_1;
    return var_2;
}

circleplayanim( var_0, var_1 )
{
    foreach ( var_3 in self.visualents )
        var_3 scriptmodelplayanim( "mp_br_pubg_circle_shrink", "br_circle", var_0, var_1 );
}

circlepauseanim()
{
    foreach ( var_1 in self.visualents )
        var_1 _meth_84CA( 1 );
}

movecircle()
{
    level endon( "game_ended" );
    self.centerent.origin = self._id_6EB7[0];
    self._id_9297 = gettime();
    self._id_36AD = self._id_9297 + self.move_time * 1000;
    var_0 = ( self._id_36AD - self._id_9297 ) / 1000;
    var_1 = self._id_78CA - self.radius_end;
    var_2 = 164.778;
    var_3 = var_1 / var_0;
    var_4 = var_3 / var_2;
    var_5 = circleanimstartoffset( self._id_78CA );
    circleplayanim( var_5, var_4 );
    level thread stopanimationatradius( self );
    self._id_08BE = 1;

    for ( var_6 = 1; var_6 < self._id_6EB7.size; var_6++ )
    {
        var_7 = distance2d( self._id_6EB7[var_6 - 1], self._id_6EB7[var_6] );
        var_8 = var_7 / self.move_speed;
        self.centerent _meth_82B1( self._id_6EB7[var_6], var_8 );
        self.centerent waittill( "movedone" );
    }
}

stopanimationatradius( var_0 )
{
    level endon( "game_ended" );
    var_1 = ( var_0._id_36AD - gettime() ) / 1000;
    wait( var_1 );
    var_0 circlepauseanim();
}

playercircleaudio()
{
    var_0 = self;
    var_0 endon( "death" );
    var_0 endon( "disconnect" );

    while ( !level.circleobjective._id_08BE )
        waitframe();

    var_1 = level.circleobjective.centerent getentitynumber();
    var_2 = level.circleobjective.radiusent getentitynumber();
    var_0 _meth_85A7( "BRModeInit", var_1, var_2 );
}

playermonitorcircle()
{
    self endon( "death" );
    self endon( "disconnect" );
    var_0 = 1000;
    var_1 = 10;
    var_2 = 500;
    var_3 = 0;
    var_4 = 0;
    var_5 = 0;

    while ( !level.circleobjective._id_08BE )
        waitframe();

    for (;;)
    {
        var_6 = level.circleobjective circleobjectivecurretradius();
        var_7 = var_6 * var_6;
        var_8 = _func_211( self.origin, level.circleobjective.centerent.origin );
        var_9 = var_8 > var_7;

        if ( var_9 )
        {
            if ( !var_3 )
            {
                self _meth_82FF( "ui_br_is_out_of_bounds", 1 );
                var_4 = gettime();
                var_5 = gettime() + var_0;
            }

            if ( gettime() >= var_5 )
            {
                self _meth_8059( var_1, level.circleobjective.centerent.origin );
                var_5 = var_5 + var_2;
            }
        }
        else if ( !var_3 )
            self _meth_82FF( "ui_br_is_out_of_bounds", 0 );

        waitframe();
        var_3 = var_9;
    }
}

circleobjectivecurretradius()
{
    var_0 = gettime() - self._id_9297;
    var_1 = self._id_36AD - self._id_9297;
    var_2 = min( var_0 / var_1, 1 );
    var_3 = self._id_78CA - self.radius_end;
    var_4 = self._id_78CA - var_2 * var_3;
    return max( var_4, self.radius_end );
}

weaponenumtostring( var_0 )
{
    switch ( var_0 )
    {
        case 0:
            return "AR";
        case 1:
            return "AR Semi";
        case 2:
            return "SMG";
        case 3:
            return "LMG";
        case 4:
            return "Sniper";
        case 5:
            return "Shotgun";
        case 6:
            return "Pistol";
        case 7:
            return "Launcher";
        case 8:
            return "Melee";
        default:
            return "Unknown";
    }
}

initloot()
{
    level.brloot = [];
    level.brloot[0] = [];
    level.brloot[1] = [];
    level.brlootchancetotal = [];
    level.brlootchancetotal[0] = 0.0;
    level.brlootchancetotal[1] = 0.0;
    addlootweapon( "m1941_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 0 );
    addlootweapon( "stg44_mp", 3.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 0 );
    addlootweapon( "fg42_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 0 );
    addlootweapon( "bar_mp", 1.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 1.0, 1.0, 0 );
    addlootweapon( "svt40_mp", 5.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 1 );
    addlootweapon( "m1a1_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 1 );
    addlootweapon( "m1garand_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 1 );
    addlootweapon( "greasegun_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 2 );
    addlootweapon( "ppsh41_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 2 );
    addlootweapon( "type100_mp", 4.0, 1, ( 3, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 2 );
    addlootweapon( "mp28_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 2 );
    addlootweapon( "thompson_mp", 0.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 2 );
    addlootweapon( "mp40_mp", 1.0, 1, ( 3, 0, 0 ), ( 0, 0, 0 ), "orange", 3.0, 1.0, 1.0, 2 );
    addlootweapon( "lewis_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 3 );
    addlootweapon( "mg15_mp", 4.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 3 );
    addlootweapon( "bren_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 3 );
    addlootweapon( "mg42_mp", 1.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 3.0, 1.0, 1.0, 3 );
    addlootweapon( "karabin_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 4 );
    addlootweapon( "leeenfield_mp", 3.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 4 );
    addlootweapon( "springfield_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 4 );
    addlootweapon( "kar98_mp", 1.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 1.0, 1.0, 4 );
    addlootweapon( "winchester1897_mp", 4.0, 1, ( 3, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 5 );
    addlootweapon( "m30_mp", 0.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 5 );
    addlootweapon( "walther_mp", 1.0, 1, ( 0, 0, 0 ), ( 0, 0, 0 ), "orange", 3.0, 1.0, 1.0, 5 );
    addlootweapon( "model21_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 5 );
    addlootweapon( "luger_mp", 15.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 6 );
    addlootweapon( "m1911_mp", 0.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 6 );
    addlootweapon( "m712_mp", 15.0, 1, ( 10, 0, 0 ), ( 0, 0, 0 ), "orange", 1.0, 0.0, 0.0, 6 );
    addlootweapon( "panzerschreck_mp", 0.0, 1, ( 5, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.0, 0.0, 7 );
    addlootweapon( "bazooka_mp", 1.0, 1, ( 12, 0, 0 ), ( 0, 0, 0 ), "orange", 2.0, 0.0, 0.0, 7 );
    addlootpickup( "ammo", 10.0, 0, ( 0, 0, -10 ), ( 0, 0, 0 ), "blue", "usa_foragepack_org1", &"MPUI_MTX1_BR_PICKUP_AMMO", ::onpickupammo );
    addlootpickup( "armor", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "blue", "raid_deployable_armor", &"MPUI_MTX1_BR_PICKUP_ARMOR", ::onpickuparmor, ::canpickuparmor );
    addlootpickup( "medkit", 10.0, 0, ( 0, 0, 0 ), ( 90, 0, 0 ), "red", "npc_throwable_usa_morale_health", &"MPUI_MTX1_BR_PICKUP_MEDKIT", ::onpickupmedkit, ::canpickupmedkit );
    addlootpickup( "frag_grenade_mp", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "yellow", "npc_usa_frag", &"MPUI_MTX1_BR_PICKUP_FRAG", ::onpickuplethal );
    addlootpickup( "semtex_mp", 3.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "yellow", "npc_eng_n74_mk1_sticky", &"MPUI_MTX1_BR_PICKUP_STICKY", ::onpickuplethal );
    addlootpickup( "smoke_grenade_mp", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "npc_usa_m18_smoke", &"MPUI_MTX1_BR_PICKUP_SMOKE", ::onpickuptactical );
    addlootpickup( "stun_grenade_mp", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "npc_eng_no69_stun", &"MPUI_MTX1_BR_PICKUP_STUN", ::onpickuptactical );
    addlootpickup( "perk_agility", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_agility_3d", &"MP_PERK_PICKUP_FASTHANDS", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_anteup", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_anteup_3d", &"MP_PERK_PICKUP_GENERIC", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_deadsilence", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_deadsilence_3d", &"MP_PERK_PICKUP_LOWPROFILE", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_doubleagent", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_doubleagent_3d", &"MP_PERK_PICKUP_GENERIC", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_flakjacket", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_flakjacket_3d", &"MP_PERK_PICKUP_FLAKJACKET", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_gunslinger", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_gunslinger_3d", &"MP_PERK_PICKUP_GUNHO", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_lightweight", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_lightweight_3d", &"MP_PERK_PICKUP_LIGHTWEIGHT", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_marathon", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_marathon_3d", &"MP_PERK_PICKUP_GENERIC", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_marksman", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_marksman_3d", &"MP_PERK_PICKUP_GENERIC", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_perception", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_perception_3d", &"MP_PERK_PICKUP_PERIPHERALS", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_scavenger", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_scavenger_3d", &"MP_PERK_PICKUP_SCAVENGER", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_dexterity", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_shieldofhand_3d", &"MP_PERK_PICKUP_DEXTERITY", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_strongarm", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_strongarm_3d", &"MP_PERK_PICKUP_GENERIC", ::onpickupperk, ::canpickupperk );
    addlootpickup( "perk_tacticalmask", 10.0, 0, ( 0, 0, 0 ), ( 0, 0, 0 ), "green", "perk_tacticalmask_3d", &"MP_PERK_PICKUP_TOUGHNESS", ::onpickupperk, ::canpickupperk );
    waittillframeend;
    initlootlocations();
    level.brlootlocationnext = 0;
    level.brlootlocationnum = level.brlootlocations[0].size;
    level.brlootlocations[0] = common_scripts\utility::array_randomize( level.brlootlocations[0] );
    spawnlootset( "luger_mp", 20 );
    spawnlootset( "m712_mp", 20 );
    spawnlootset( "winchester1897_mp", 4 );
    spawnlootset( "walther_mp", 1 );
    spawnlootset( "leeenfield_mp", 4 );
    spawnlootset( "kar98_mp", 1 );
    spawnlootset( "mg15_mp", 4 );
    spawnlootset( "mg42_mp", 1 );
    spawnlootset( "type100_mp", 4 );
    spawnlootset( "mp40_mp", 2 );
    spawnlootset( "svt40_mp", 4 );
    spawnlootset( "stg44_mp", 2 );
    spawnlootset( "bar_mp", 1 );
    spawnlootset( "armor", 30 );
    spawnlootset( "ammo", 30 );
    spawnlootset( "medkit", 20 );
    spawnlootset( "frag_grenade_mp", 10 );
    spawnlootset( "semtex_mp", 10 );
    spawnlootset( "smoke_grenade_mp", 10 );
    spawnlootset( "stun_grenade_mp", 10 );
    spawnlootset( "perk_agility", 5 );
    spawnlootset( "perk_anteup", 5 );
    spawnlootset( "perk_deadsilence", 5 );
    spawnlootset( "perk_doubleagent", 5 );
    spawnlootset( "perk_flakjacket", 5 );
    spawnlootset( "perk_gunslinger", 5 );
    spawnlootset( "perk_lightweight", 5 );
    spawnlootset( "perk_marathon", 5 );
    spawnlootset( "perk_marksman", 5 );
    spawnlootset( "perk_perception", 5 );
    spawnlootset( "perk_scavenger", 5 );
    spawnlootset( "perk_dexterity", 5 );
    spawnlootset( "perk_strongarm", 5 );
    spawnlootset( "perk_tacticalmask", 5 );
}

addlootcommon( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    if ( isdefined( level.brloot[0][var_0] ) )
        return;

    var_6 = spawnstruct();
    var_6.name = var_0;
    var_6.originoffset = var_3;
    var_6.anglesoffset = var_4;
    var_6._id_3F74 = var_5;
    var_6.loottype = 0;
    var_6._id_9040 = 0;
    var_6.chancerangestart = [];
    var_6.chancerangeend = [];
    var_7 = [];
    var_7[0] = var_1;
    var_7[1] = common_scripts\utility::_id_98E7( var_2, var_1, 0.0 );

    for ( var_8 = 0; var_8 < 2; var_8++ )
    {
        var_6.chancerangestart[var_8] = level.brlootchancetotal[var_8];
        level.brlootchancetotal[var_8] = level.brlootchancetotal[var_8] + var_7[var_8];
        var_6.chancerangeend[var_8] = level.brlootchancetotal[var_8];
        level.brloot[var_8][var_0] = var_6;
    }

    return var_6;
}

addlootpickup( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    var_10 = addlootcommon( var_0, var_1, var_2, var_3, var_4, var_5 );
    var_10.loottype = 2;
    var_10.model = var_6;
    var_10._id_00C5 = var_7;
    var_10.onpickupfunc = var_8;
    var_10.canpickupfunc = var_9;
}

addlootweapon( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    var_10 = addlootcommon( var_0, var_1, var_2, var_3, var_4, var_5 );
    var_10.loottype = 1;
    var_10.startclips = var_6;
    var_10.attachment1chance = var_7;
    var_10.attachment2chance = var_8;
    var_10.weapontypeenum = var_9;
}

initlootlocations()
{
    level.brlootlocations = [];

    for ( var_0 = 0; var_0 < 3; var_0++ )
        level.brlootlocations[var_0] = [];

    var_1 = common_scripts\utility::_id_46B7( "br_loot_location", "targetname" );
    common_scripts\utility::_id_0FB2( var_1, ::lootlocationinit, 0 );
    var_1 = common_scripts\utility::_id_46B7( "br_loot_location_force_use", "targetname" );
    common_scripts\utility::_id_0FB2( var_1, ::lootlocationinit, 1 );

    if ( !var_1.size )
        addpathnodelootlocations();
}

lootlocationinit( var_0 )
{
    self.origin = self.origin + ( 0, 0, lootgroundoffset() );
    self.forceuse = var_0;
    level.brlootlocations[0][level.brlootlocations[0].size] = self;

    if ( var_0 )
        level.brlootlocations[1][level.brlootlocations[1].size] = self;
    else
        level.brlootlocations[2][level.brlootlocations[2].size] = self;
}

addpathnodelootlocations()
{
    var_0 = 2;
    var_1 = 25;
    var_2 = lootpathnodesoutside();
    var_3 = lootpathnodesinsideparial();
    var_4 = lootpathnodesinsidecomplete();
    level.brinteriors = [];
    var_5 = getallnodes();
    var_5 = common_scripts\utility::array_randomize( var_5 );

    foreach ( var_7 in var_5 )
    {
        if ( var_7.type != "Path" )
            continue;

        updateinteriorlocations( var_7 );
    }

    var_9 = [];

    foreach ( var_12, var_11 in level.brinteriors )
        var_9[var_12] = level.brinteriors[var_12].size;

    foreach ( var_7 in var_5 )
    {
        var_14 = 0;

        if ( common_scripts\utility::_id_562E( var_7.noloot ) )
            continue;

        if ( var_7.type != "Path" )
            continue;

        if ( _func_200( var_7, 1 ) )
        {
            if ( randomfloat( 1.0 ) > var_2 )
                continue;
        }
        else if ( _func_200( var_7, 0 ) )
        {
            if ( randomfloat( 1.0 ) > var_3 )
                continue;
        }
        else
        {
            if ( isdefined( var_7.interiorindex ) )
            {
                if ( level.brinteriors[var_7.interiorindex].size <= var_0 )
                    continue;

                if ( var_9[var_7.interiorindex] > 0 )
                    var_9[var_7.interiorindex] = var_9[var_7.interiorindex] - var_1;
            }

            if ( !var_14 && randomfloat( 1.0 ) > var_4 )
                continue;
        }

        var_15 = ( 0, randomfloatrange( 0, 360 ), 0 );
        var_16 = addlootlocation( var_7.origin, var_15, var_14 );
        var_16._id_010D = var_7;
        setnolootonconenctednodes( var_7, var_7, 0, lootpathnodesmindist() );
    }
}

updateinteriorlocations( var_0 )
{
    if ( !nodeneedsinteriorindex( var_0 ) )
        return;

    var_1 = level.brinteriors.size;
    level.brinteriors[var_1] = [];
    var_0.interiorindex = var_1;
    level.brinteriors[var_1][0] = var_0;

    for ( var_2 = 0; var_2 < level.brinteriors[var_1].size; var_2++ )
    {
        var_3 = level.brinteriors[var_1][var_2];
        var_4 = _func_204( var_3 );

        foreach ( var_6 in var_4 )
        {
            if ( nodeneedsinteriorindex( var_6 ) )
            {
                var_6.interiorindex = var_1;
                var_7 = level.brinteriors[var_1].size;
                level.brinteriors[var_1][var_7] = var_6;
            }
        }
    }
}

nodeneedsinteriorindex( var_0 )
{
    return !isdefined( var_0.interiorindex ) && !_func_200( var_0, 0 );
}

setinteriorindex( var_0, var_1 )
{
    if ( isdefined( var_0.interiorindex ) )
        return;

    if ( _func_200( var_0, 0 ) )
        return;

    var_0.interiorindex = var_1;
    var_2 = level.brinteriors[var_1].size;
    level.brinteriors[var_1][var_2] = var_0;
    var_3 = _func_204( var_0 );

    foreach ( var_5 in var_3 )
        setinteriorindex( var_5, var_1 );
}

setnolootonconenctednodes( var_0, var_1, var_2, var_3 )
{
    var_1.loopcheck = var_0;
    var_4 = _func_204( var_1 );

    foreach ( var_6 in var_4 )
    {
        if ( isdefined( var_6.loopcheck ) && var_6.loopcheck == var_0 )
            continue;

        var_7 = distance( var_1.origin, var_6.origin );

        if ( var_2 + var_7 < var_3 )
        {
            var_6.noloot = 1;

            if ( !isdefined( var_0.nolootnodes ) )
                var_0.nolootnodes = [];

            var_0.nolootnodes[var_0.nolootnodes.size] = var_6;
            setnolootonconenctednodes( var_0, var_6, var_2 + var_7, var_3 );
        }
    }
}

lootlocationcreate( var_0, var_1, var_2 )
{
    var_3 = spawnstruct();
    var_3.origin = var_0;
    var_3.angles = var_1;

    if ( common_scripts\utility::_id_562E( var_2 ) )
        var_3.targetname = "br_loot_location_force_use";
    else
        var_3.targetname = "br_loot_location";

    return var_3;
}

addlootlocation( var_0, var_1, var_2 )
{
    var_3 = lootlocationcreate( var_0, var_1, var_2 );
    common_scripts\utility::_id_096C( var_3 );
    return var_3;
}

spawnloot( var_0, var_1 )
{
    switch ( var_0.loottype )
    {
        case 1:
            spawnlootweapon( var_0, var_1 );
            break;
        case 2:
            spawnlootpickup( var_0, var_1 );
            break;
        case 0:
        default:
            break;
    }
}

spawnlootset( var_0, var_1 )
{
    var_2 = level.brloot[0][var_0];

    for ( var_3 = 0; var_3 < var_1 && level.brlootlocationnext < level.brlootlocationnum; var_3++ )
    {
        spawnloot( var_2, level.brlootlocations[0][level.brlootlocationnext] );
        level.brlootlocationnext++;
    }
}

canpickuparmor( var_0, var_1 )
{
    if ( isdefined( var_1._id_5D2E ) && isdefined( var_1._id_6089 ) && var_1._id_5D2E >= var_1._id_6089 )
    {
        var_1 iprintlnbold( &"MPUI_MTX1_BR_MAX_ARMOR" );
        return 0;
    }

    return 1;
}

onpickuparmor( var_0, var_1 )
{
    var_1 notify( "give_light_armor" );

    if ( !isdefined( var_1._id_5D2E ) )
    {
        var_1._id_5D2E = 0;
        var_1 thread _id_052C::_id_7CE7();
        var_1 thread _id_052C::_id_7CE8();
    }

    var_1._id_6089 = 150;

    if ( var_1._id_5D2E >= var_1._id_6089 )
        return;

    var_1._id_5D2E = var_1._id_5D2E + 50;

    if ( var_1._id_5D2E >= var_1._id_6089 )
        var_1._id_5D2E = var_1._id_6089;

    var_1 _id_052C::_id_86BC( var_1._id_5D2E );
}

getlootspecialty( var_0 )
{
    if ( var_0 == "perk_agility" )
        return "specialty_sprintreload";

    if ( var_0 == "perk_anteup" )
        return "specialty_unwrapper";

    if ( var_0 == "perk_deadsilence" )
        return "specialty_quieter";

    if ( var_0 == "perk_doubleagent" )
        return "specialty_silentmovement";

    if ( var_0 == "perk_flakjacket" )
        return "specialty_blastshield2";

    if ( var_0 == "perk_gunslinger" )
        return "specialty_sprintfire";

    if ( var_0 == "perk_lightweight" )
        return "specialty_lightweight";

    if ( var_0 == "perk_marathon" )
        return "specialty_marathon";

    if ( var_0 == "perk_marksman" )
        return "specialty_marksman";

    if ( var_0 == "perk_perception" )
        return "specialty_perception";

    if ( var_0 == "perk_savenger" )
        return "specialty_quickswap";

    if ( var_0 == "perk_dexterity" )
        return "specialty_fastreload";

    if ( var_0 == "perk_strongarm" )
        return "specialty_stalker";

    if ( var_0 == "perk_tacticalmask" )
        return "specialty_stun_resistance";
}

getlootspecialty2( var_0 )
{
    if ( var_0 == "perk_tacticalmask" )
        return "specialty_immunesmoke";
}

canpickupperk( var_0, var_1 )
{
    return 1;
}

onpickupperk( var_0, var_1 )
{

}

onpickupammo( var_0, var_1 )
{
    var_2 = var_1 getweaponlistprimaries();

    foreach ( var_4 in var_2 )
    {
        if ( maps\mp\_utility::iscacprimaryweapon( var_4 ) || level._id_808C && maps\mp\_utility::iscacsecondaryweapon( var_4 ) )
        {
            var_5 = var_1 getweaponammostock( var_4 );
            var_6 = 0;
            var_7 = maps\mp\_utility::getweaponclass( var_4 );

            if ( _id_0513::_id_5684( var_4 ) || var_7 == "weapon_riot" || issubstr( var_4, "riotshield" ) )
            {

            }
            else if ( var_7 == "weapon_projectile" || issubstr( var_4, "exocrossbow" ) || issubstr( var_4, "microdronelauncher" ) )
                var_6 = weaponclipsize( var_4 );
            else if ( maps\mp\_utility::_id_5670( var_4 ) && issubstr( var_4, "grenade_launcher" ) )
                var_6 = weaponclipsize( var_4 );
            else if ( maps\mp\_utility::_id_5670( var_4 ) && issubstr( var_4, "dragon_breath" ) )
            {

            }
            else if ( _id_0513::_id_5696( var_4 ) )
                var_6 = weaponclipsize( var_4 );

            if ( var_6 > 0 )
                var_1 setweaponammostock( var_4, var_5 + var_6 );
        }
    }
}

onpickuplethal( var_0, var_1 )
{
    var_2 = var_0;
    var_3 = var_1 getweaponammoclip( var_2 );
    var_1 giveweapon( var_2 );
    var_1 _meth_8349( var_2 );
    var_1 setweaponammoclip( var_2, var_3 + 1 );
}

onpickuptactical( var_0, var_1 )
{
    var_2 = var_0;
    var_3 = var_1 getweaponammoclip( var_2 );
    var_1 giveweapon( var_2 );
    var_1 setoffhandsecondaryclass( var_2 );
    var_1 setweaponammoclip( var_2, var_3 + 1 );
}

pickuponused()
{
    self endon( "death" );

    for (;;)
    {
        self waittill( "trigger", var_0 );

        if ( !maps\mp\_utility::isreallyalive( var_0 ) )
            continue;

        if ( isdefined( self.canpickupfunc ) && !self [[ self.canpickupfunc ]]( self.lootname, var_0 ) )
            continue;

        self [[ self.onpickupfunc ]]( self.lootname, var_0 );
        break;
    }

    waittillframeend;
    self delete();
}

spawnlootinitent( var_0, var_1, var_2 )
{
    var_3 = rotatevector( var_1.originoffset, var_2.angles );
    var_0.origin = var_2.origin + var_3;
    var_0.angles = var_2.angles + var_1.anglesoffset;
    var_0.targetname = "br_loot";
    var_0.loottype = var_1.loottype;
    var_0.lootname = var_1.name;
    var_0._id_3F77 = var_2.origin;
    var_1._id_9040++;
    var_0 _meth_83FE( 0, 1 );
}

spawnlootpickup( var_0, var_1 )
{
    var_2 = spawn( "script_model", ( 0, 0, 0 ), lootpickupscriptmoverflags() );
    var_2 setmodel( var_0.model );
    var_2.onpickupfunc = var_0.onpickupfunc;
    var_2.canpickupfunc = var_0.canpickupfunc;
    spawnlootinitent( var_2, var_0, var_1 );
    var_2 makeusable();
    var_2 _meth_80CE( var_0._id_00C5 );
    var_2 thread pickuponused();
}

lootpickupscriptmoverflags()
{
    return scriptmoverspawnflagsprintuse();
}

lootweaponitemflags( var_0 )
{
    var_1 = 0;

    if ( lootdroptoground() )
        var_1 = var_1 | itemspawnflagsuspended();

    if ( weaponisakimbo( var_0 ) )
        var_1 = var_1 | itemspawnflagakimbo();

    var_1 = var_1 | itemspawnflagsprintuse();
    return var_1;
}

weaponisakimbo( var_0 )
{
    var_1 = getweaponattachments( var_0, 1 );

    foreach ( var_3 in var_1 )
    {
        if ( issubstr( var_3, "akimbo" ) )
            return 1;
    }

    return 0;
}

lootweaponsetstartammo( var_0, var_1, var_2 )
{
    var_3 = weaponclipsize( var_2 );
    var_4 = int( var_1.startclips * var_3 );

    if ( var_4 > var_3 )
    {
        var_5 = var_3;
        var_6 = var_4 - var_3;
    }
    else
    {
        var_5 = var_4;
        var_6 = 0;
    }

    if ( weaponisakimbo( var_2 ) )
        var_0 _meth_817E( var_5, var_6 * 2, var_5 );
    else
        var_0 _meth_817E( var_5, var_6 );

    var_0 _meth_86B3( 0 );
}

spawnlootweapon( var_0, var_1 )
{
    var_2 = var_0.name;
    var_3 = _func_372( var_0.name );
    var_4 = [];

    foreach ( var_6 in var_3 )
    {
        if ( var_6.size > 2 )
        {
            var_7 = getsubstr( var_6, var_6.size - 2, var_6.size );

            if ( var_7 == "_1" || var_7 == "_2" )
                var_4[var_4.size] = var_6;
        }
    }

    foreach ( var_10 in var_4 )
        var_3 = common_scripts\utility::_id_0F93( var_3, var_10 );

    var_12 = _func_3A1( var_0.name );

    foreach ( var_15, var_14 in var_12 )
        var_3 = common_scripts\utility::_id_0F93( var_3, var_14 );

    var_16 = [ "extended_mag", "telescopic_sight" ];

    foreach ( var_18 in var_16 )
    {
        var_19 = [];

        foreach ( var_6 in var_3 )
        {
            if ( issubstr( var_6, var_18 ) )
                var_19[var_19.size] = var_6;
        }

        foreach ( var_23 in var_19 )
            var_3 = common_scripts\utility::_id_0F93( var_3, var_23 );
    }

    var_26 = undefined;
    var_27 = undefined;

    if ( randomfloat( 1.0 ) < var_0.attachment1chance && var_3.size > 0 )
    {
        var_26 = common_scripts\utility::random( var_3 );

        if ( randomfloat( 1.0 ) < var_0.attachment2chance )
        {
            var_28 = tablelookuprownum( "mp/attachmentcombos_mtx12.csv", 0, var_26 );
            var_29 = _func_27B( "mp/attachmentcombos_mtx12.csv" );

            for ( var_30 = 0; var_30 < var_29; var_30++ )
            {
                var_31 = tablelookupbyrow( "mp/attachmentcombos_mtx12.csv", var_28, var_30 );

                if ( var_31 == "no" )
                {
                    var_32 = tablelookupbyrow( "mp/attachmentcombos_mtx12.csv", 0, var_30 );
                    var_3 = common_scripts\utility::_id_0F93( var_3, var_32 );
                }
            }

            if ( var_3.size > 0 )
                var_27 = common_scripts\utility::random( var_3 );
        }
    }

    if ( var_0.weapontypeenum == 4 )
    {
        if ( !isdefined( var_26 ) || var_26 == "hold_breath_1" )
            var_26 = "hold_breath_3";
        else if ( var_26 != "hold_breath_3" )
            var_27 = "hold_breath_3";
    }

    if ( isdefined( var_26 ) && isdefined( var_27 ) )
    {
        if ( stricmp( var_26, var_27 ) > 0 )
        {
            var_33 = var_26;
            var_26 = var_27;
            var_27 = var_33;
        }
    }

    if ( isdefined( var_26 ) )
    {
        var_2 = var_2 + ( "+" + var_26 );

        if ( isdefined( var_27 ) )
            var_2 = var_2 + ( "+" + var_27 );
    }

    spawnweaponitem( var_2, var_0, var_1 );
}

spawnweaponitem( var_0, var_1, var_2 )
{
    var_3 = "weapon_" + var_0;
    var_4 = spawn( var_3, ( 0, 0, 0 ), lootweaponitemflags( var_0 ) );
    spawnlootinitent( var_4, var_1, var_2 );
    lootweaponsetstartammo( var_4, var_1, var_0 );
    var_4 thread _id_0513::_id_A934();
    var_4 thread lootweaponwatchpickup();
    return var_4;
}

lootweaponwatchpickup()
{
    self endon( "death" );
    var_0 = _id_0513::_id_452C();

    for (;;)
    {
        self waittill( "trigger", var_1, var_2, var_3, var_4, var_5 );

        if ( !isdefined( var_3 ) || !isdefined( var_4 ) )
            continue;

        if ( var_3 == var_4 )
        {
            if ( var_3 )
                return;
        }
        else
            break;
    }

    if ( isdefined( var_0 ) && var_0 == var_1.primaryweapon )
        return;

    if ( isdefined( var_0 ) && var_0 == var_1._id_835A )
        return;

    var_6 = 0;
    var_7 = var_1 getweaponlistprimaries();

    foreach ( var_9 in var_7 )
    {
        if ( isdefined( var_9 ) && var_9 == "shovel_mp" )
        {
            var_6 = 1;
            break;
        }
    }

    if ( var_6 )
    {
        if ( isdefined( var_2 ) )
        {
            var_1 takeweapon( "shovel_mp" );
            _id_0513::updateplayervariablesforweaponexchange( var_1, "shovel_mp", var_0 );
            var_11 = var_2 _id_0513::_id_452C();
            var_1 giveweapon( var_11 );
            var_12 = var_2 _meth_85F2();
            var_1 setweaponammoclip( var_11, var_12["clip_ammo"] );
            var_1 setweaponammostock( var_11, var_12["stock_ammo"] );
            var_2 delete();
        }
        else
        {
            var_13 = var_1.currentweapon;

            if ( shouldrestoreweapontoplayer( var_13, var_1 ) )
            {
                var_1 takeweapon( "shovel_mp" );
                _id_0513::updateplayervariablesforweaponexchange( var_1, "shovel_mp", var_0 );
                var_1 giveweapon( var_13 );
                var_1 setweaponammoclip( var_13, 0 );
                var_1 setweaponammostock( var_13, 0 );
            }
        }
    }
    else if ( isdefined( var_2 ) )
    {
        var_11 = var_2 _id_0513::_id_452C();
        var_14 = var_1 dropweaponbattleroyale( var_11 );
        var_15 = var_2 _meth_85F2();
        var_16 = var_15["clip_ammo"];
        var_17 = var_15["stock_ammo"];
        var_18 = var_15["clip_ammo_left"];

        if ( !isdefined( var_18 ) )
            var_18 = 0;

        var_14 _meth_817E( var_16, var_17, var_18 );
        _id_0513::updateplayervariablesforweaponexchange( var_1, var_11, var_0 );
        var_2 delete();
    }
}

shouldrestoreweapontoplayer( var_0, var_1 )
{
    if ( !isdefined( var_0 ) )
        return 0;

    if ( var_0 == "shovel_mp" )
        return 0;

    if ( var_1 _meth_8319( var_0 ) )
        return 0;

    var_2 = maps\mp\_utility::_id_4431( var_0 );

    if ( !isdefined( level.brloot[0][var_2] ) )
        return 0;

    if ( level.brloot[0][var_2].loottype != 1 )
        return 0;

    return 1;
}

spawnlootfx( var_0, var_1 )
{
    var_0 endon( "death" );

    if ( var_0.loottype == 1 )
    {
        if ( !( var_0.spawnflags & itemspawnflagsuspended() ) )
        {
            var_2 = var_0.origin + ( 0, 0, 1 );

            while ( var_2 != var_0.origin )
            {
                var_2 = var_0.origin;
                waitframe();
            }
        }
    }

    var_3 = spawnfx( level.br_fx["weapon_pickup_" + var_1], var_0._id_3F77 );
    triggerfx( var_3 );
    var_0 waittill( "trigger" );
    var_3 delete();
}

lootdensity()
{
    return getdvarfloat( "scr_br_loot_density", 0.6 );
}

lootdroptoground()
{
    return getdvarint( "scr_br_loot_drop_to_ground", 1 );
}

lootgroundoffset()
{
    return getdvarfloat( "scr_br_loot_ground_offset", 10 );
}

itemspawnflagsuspended()
{
    return 1;
}

itemspawnflagakimbo()
{
    return 4;
}

itemspawnflagsprintuse()
{
    return 16;
}

scriptmoverspawnflagsprintuse()
{
    return 16;
}

maxspawnedlootitems()
{
    return 100;
}

lootpathnodesoutside()
{
    return getdvarfloat( "scr_br_loot_path_nodes_outside", 0.02 );
}

lootpathnodesinsideparial()
{
    return getdvarfloat( "scr_br_loot_path_nodes_inside_partial", 0.0 );
}

lootpathnodesinsidecomplete()
{
    return getdvarfloat( "scr_br_loot_path_nodes_inside_complete", 1.0 );
}

lootpathnodesmindist()
{
    return getdvarint( "scr_br_loot_path_nodes_min_dist", 100 );
}

lootgetgroundpos( var_0 )
{
    return bullettrace( var_0 + ( 0, 0, 10 ), var_0 + ( 0, 0, -1000 ), 0, self, 0, 0, 0, 0, 1, 1, 0 )["position"];
}

playergetcurrentweapon()
{
    var_0 = self getcurrentweapon();

    if ( var_0 == "none" )
    {
        foreach ( var_2 in self getweaponlistprimaries() )
        {
            if ( self getammocount( var_2 ) != 0 )
            {
                var_0 = var_2;
                break;
            }
        }
    }

    if ( var_0 == "none" )
        var_0 = self getweaponlistprimaries()[0];

    if ( _id_028D::_id_5855() )
    {
        if ( isdefined( self._id_A99F ) )
            var_0 = self._id_A99F;
    }

    if ( !isdefined( var_0 ) )
        var_0 = "none";

    return var_0;
}

playermedkitinit()
{
    self.usingmedkit = 0;
    self.nummedkits = 0;
}

canpickupmedkit( var_0, var_1 )
{
    if ( isdefined( var_1.nummedkits ) && var_1.nummedkits >= 3 )
    {
        var_1 iprintlnbold( &"MPUI_MTX1_BR_MAX_MEDKITS" );
        return 0;
    }

    return 1;
}

onpickupmedkit( var_0, var_1 )
{
    var_1.nummedkits++;
}

playermedkithud()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "death" );
    waittillframeend;
    var_0 = 9999;

    for (;;)
    {
        if ( self.nummedkits != var_0 )
        {
            self _meth_82FF( "ks_icon" + common_scripts\utility::_id_9AAD( 1 ), 7 );
            self _meth_82FF( "ks_selectedIndex", 1 );
            self _meth_82FF( "ks_count" + common_scripts\utility::_id_9AAD( 1 ), self.nummedkits );
            self _meth_82FF( "ks_hasStreak", common_scripts\utility::_id_98E7( self.nummedkits > 0, 2, 0 ) );
            var_0 = self.nummedkits;
        }

        waitframe();
    }
}

playermedkitusemonitor()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "death" );

    for (;;)
    {
        self waittill( "tryUseMedkit" );

        if ( !self _meth_8648() )
            continue;

        if ( self.health >= self.maxhealth )
        {
            self iprintlnbold( &"MPUI_MTX1_BR_FULL_HEALTH" );
            continue;
        }

        if ( common_scripts\utility::_id_562E( self.usingmedkit ) )
            continue;

        if ( self.nummedkits > 0 )
        {
            thread playermedkitinterruptwatcher();
            playermedkitusebegin();
            playermedkituseend();
            continue;
        }

        self iprintlnbold( &"MPUI_MTX1_BR_NO_MEDKITS" );
    }
}

playermedkitusebegin()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "death" );
    self endon( "medkit_cancel" );
    self.usingmedkit = 1;
    self _meth_8304( 0 );
    self _meth_8308( 0 );
    self _meth_8307( 0 );
    self _meth_812B( 0 );
    self _meth_8331();
    var_0 = playergetcurrentweapon();
    self giveweapon( "medkit_mp" );
    self switchtoweapon( "medkit_mp" );
    wait 2;

    while ( isdefined( self _meth_85C2() ) )
        waitframe();

    if ( isdefined( var_0 ) && var_0 != "none" )
        self switchtoweapon( var_0 );

    self.nummedkits--;
    var_1 = self.health + 100;
    var_2 = min( 1.0, var_1 / self.maxhealth );
    self _meth_8058( var_2 );
    thread playerhealoverlay();
}

playermedkitinterruptwatcher()
{
    level endon( "game_ended" );
    self endon( "disconnect" );
    self endon( "death" );
    self endon( "medkit_end" );

    for (;;)
    {
        self waittill( "weapon_switch_started", var_0 );

        if ( var_0 == "medkit_mp" )
            continue;

        self notify( "medkit_cancel" );
        break;
    }
}

playermedkituseend()
{
    self notify( "medkit_end" );
    self takeweapon( "medkit_mp" );
    self _meth_8304( 1 );
    self _meth_8308( 1 );
    self _meth_8307( 1 );
    self _meth_812B( 1 );
    self _meth_8332();
    self.usingmedkit = 0;
}

playerprekillbattleroyale( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 )
{
    self.victimcurrentlethal = var_2 _meth_834A();
    self.victimcurrenttactical = var_2 getoffhandsecondaryclass();
    self.victimcurrentweapon = var_2 getcurrentweapon();

    if ( self.victimcurrentweapon == "medkit_mp" )
        var_2 takeweapon( "medkit_mp" );
}

playerhealoverlay()
{
    self endon( "disconnect" );
    var_0 = 1;
    var_1 = newclienthudelem( self );
    var_1.x = 0;
    var_1.y = 0;
    var_1._id_00C6 = "fullscreen";
    var_1._id_01CA = "fullscreen";
    var_1 setshader( "combathigh_overlay", 640, 480 );
    var_1.alpha = 1;
    var_1 fadeovertime( var_0 );
    var_1.alpha = 0;
    common_scripts\utility::_id_A71A( var_0, "death" );
    var_1 destroy();
}

playdeathstingersforteams( var_0 )
{
    if ( !isplayer( var_0 ) )
        return;

    var_1 = var_0.team;
    var_2 = maps\mp\_utility::getotherteam( var_1 );
    level thread maps\mp\_utility::playsoundonplayers( "mp_obj_notify_pos_med", var_2 );
    level thread maps\mp\_utility::playsoundonplayers( "mp_obj_notify_neg_med", var_1 );
}

callincarepackage( var_0, var_1, var_2 )
{
    if ( isdefined( var_0 ) )
    {
        if ( !_func_30D( var_0 ) )
            var_0 = 0;

        wait( var_0 );
    }

    var_3 = undefined;
    var_4 = common_scripts\utility::array_randomize( level.players );
    var_3 = var_4[0];

    if ( !isdefined( var_3 ) )
        return;

    if ( !isdefined( var_1 ) )
        var_1 = var_3.pers["team"];

    if ( !isdefined( var_2 ) )
        var_2 = "v2_rocket";

    var_5 = self.circleobjective._id_6EB7[self.circleobjective._id_6EB7.size - 1];

    if ( !isdefined( var_5 ) )
        return;

    var_6 = _id_0527::_id_4570();
    var_3 thread _id_0527::_id_9302( var_3._id_5CC6, [ var_5 ], [ var_6 ], "carepackage", undefined, var_1, var_2 );
    var_7 = level common_scripts\utility::_id_A74D( "airdropInbound", 20 );

    if ( isdefined( var_7 ) && var_7 == "timeout" )
        return;

    thread maps\mp\_utility::teamplayercardsplash( "raids_airdrop_incoming", var_3, var_1 );
}
