// S2 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    _id_04D4::init();
    maps\mp\gametypes\_callbacksetup::setupcallbacks();
    _id_04D4::setupcallbacks();

    if ( isusingmatchrulesdata() )
    {
        level._id_5300 = ::_id_5300;
        [[ level._id_5300 ]]();
        level thread maps\mp\_utility::_id_7C13();
    }
    else
    {
        maps\mp\_utility::registertimelimitdvar( level.gametype, 2.5 );
        maps\mp\_utility::registerscorelimitdvar( level.gametype, 0 );
        maps\mp\_utility::registerroundlimitdvar( level.gametype, 4 );
        maps\mp\_utility::registerwinlimitdvar( level.gametype, 0 );
        maps\mp\_utility::registernumlivesdvar( level.gametype, 1 );
        maps\mp\_utility::registerhalftimedvar( level.gametype, 0 );
        level._id_6031 = 0;
        level._id_6035 = 0;
    }

    level._id_5A74 = 1;
    level._id_5A6F = 0;
    level.disabledivisionstats = 1;
    level.disabledivisionpassives = 1;
    level.disabledivisionskills = 1;
    level.mgnestsdisabled = 1;
    level._id_6BA7 = ::_id_6BA7;
    level._id_6BAF = ::_id_6BAF;
    level._id_6B7B = ::_id_6B7B;
    level._id_6B5C = ::_id_6B5C;
    level._id_6B7F = ::_id_6B7F;
    level._id_6BB6 = ::_id_6BB6;
    level._id_3FDD = ::applyspyperks;
    level._id_62AD = ::modifyplayerdamagespymode;

    if ( level._id_6031 || level._id_6035 )
        level._id_62AD = maps\mp\gametypes\_damage::_id_3FC8;

    level.roundbasedffa = 1;
    setteammode( "ffa" );
    maps\mp\_utility::_id_873B( 0 );
    game["dialog"]["gametype"] = "spy_intro";
    game["dialog"]["defense_obj"] = "gbl_start";
    game["dialog"]["offense_obj"] = "gbl_start";

    if ( getdvarint( "2043" ) )
        game["dialog"]["gametype"] = "hc_" + game["dialog"]["gametype"];

    level.spy_fx = [];
    level.spy_class_counts = [];

    for ( var_0 = 0; var_0 < 3; var_0++ )
        level.spy_class_counts[var_0] = 0;

    level.spy_class_maxs = [ [ 0, 0, 0 ], [ 1, 0, 0 ], [ 1, 0, 1 ], [ 1, 1, 1 ], [ 2, 1, 1 ], [ 3, 1, 1 ], [ 3, 1, 2 ], [ 4, 1, 2 ], [ 4, 2, 2 ], [ 5, 2, 2 ], [ 6, 2, 2 ], [ 6, 2, 3 ], [ 7, 2, 3 ], [ 8, 2, 3 ], [ 8, 3, 3 ], [ 9, 3, 3 ], [ 9, 3, 4 ], [ 10, 3, 4 ], [ 11, 3, 4 ] ];
    thread onplayerconnect();
    thread maps\mp\gametypes\_spy_loot::init();
}

_id_5300()
{
    maps\mp\_utility::_id_8653( 1 );
    var_0 = getmatchrulesdata( "commonOption", "timeLimit" );
    setdynamicdvar( "scr_spy_timelimit", var_0 );
    maps\mp\_utility::registertimelimitdvar( "spy", var_0 );
    var_1 = getmatchrulesdata( "commonOption", "scoreLimit" );
    setdynamicdvar( "scr_spy_roundlimit", var_1 );
    maps\mp\_utility::registerroundlimitdvar( "spy", var_1 );
    setdynamicdvar( "scr_spy_winlimit", 0 );
    maps\mp\_utility::registerwinlimitdvar( "spy", 0 );
    setdynamicdvar( "scr_spy_scorelimit", 0 );
    maps\mp\_utility::registerscorelimitdvar( "spy", 0 );
}

_id_6BB6()
{
    spy_endgame( 0, game["end_reason"]["time_limit_reached"] );
}

spy_endgame( var_0, var_1 )
{
    foreach ( var_3 in level.players )
    {
        if ( !isdefined( var_3.spyclass ) )
            return;

        if ( maps\mp\gametypes\_spy_util::spyclassfriendlycheck( var_0, var_3.spyclass ) )
        {
            var_3.pers["score"] = var_3.pers["score"] + 1;
            var_3._id_008F = var_3._id_008F + var_3.pers["score"];
        }
    }

    var_5 = _id_04D2::_id_450A();
    thread maps\mp\gametypes\_gamelogic::_id_36B9( var_5, var_1 );
}

onplayerconnect()
{
    for (;;)
    {
        level waittill( "connected", var_0 );
        var_0._id_008F = var_0.pers["score"];
        var_0 thread playerassignspyclass();
        var_0 thread playerdisconnect();
        var_0 thread _id_6B74();
    }
}

_id_6B74()
{
    for (;;)
    {
        self waittill( "death" );
        playercleanupheadicon();
    }
}

playerdisconnect()
{
    self waittill( "disconnect" );
    thread playerremovespyclass();
    spycheckforwin();
}

_id_6BAF()
{
    maps\mp\_utility::gameflaginit( "spy_loot_done", 0 );
    setclientnamemode( "auto_change" );
    maps\mp\_utility::setobjectivetext( "allies", &"OBJECTIVES_DM" );
    maps\mp\_utility::setobjectivetext( "axis", &"OBJECTIVES_DM" );

    if ( level.splitscreen )
    {
        maps\mp\_utility::setobjectivescoretext( "allies", &"OBJECTIVES_DM" );
        maps\mp\_utility::setobjectivescoretext( "axis", &"OBJECTIVES_DM" );
    }
    else
    {
        maps\mp\_utility::setobjectivescoretext( "allies", &"OBJECTIVES_DM_SCORE" );
        maps\mp\_utility::setobjectivescoretext( "axis", &"OBJECTIVES_DM_SCORE" );
    }

    maps\mp\_utility::setobjectivehinttext( "allies", &"OBJECTIVES_DM_HINT" );
    maps\mp\_utility::setobjectivehinttext( "axis", &"OBJECTIVES_DM_HINT" );
    _id_050D::_id_10E4();
    level._id_A239 = 1;
    var_0[0] = "spy";
    var_0[1] = "blocker_spy";
    _id_04D1::main( var_0 );
    level._id_7895 = 1;
    level._id_90E2["none"].allownonespectate = 1;
    thread spylootphase();
    thread serverhud();
}

spylootphase()
{
    var_0 = getdvarint( "scr_spy_loot_phase_time", 30 );
    var_1 = maps\mp\gametypes\_hud_util::_id_282B( "default", 2.0 );
    var_1 maps\mp\gametypes\_hud_util::setpoint( "CENTER", "CENTER", 0, -50 );
    var_1.label = &"MP_SPY_LOOT_PHASE";
    var_1 settimer( var_0 );
    wait( var_0 );
    var_1 destroy();
    maps\mp\_utility::gameflagset( "spy_loot_done" );
}

serverhud()
{
    maps\mp\_utility::gameflagwait( "spy_loot_done" );
    var_0 = 32;
    var_1 = maps\mp\gametypes\_hud_util::_id_2829( "default", 2.0 );
    var_1 maps\mp\gametypes\_hud_util::setpoint( "LEFT", "LEFT", var_0, -50 );
    var_1.label = &"MP_SPY_NUM_CIVILIANS";
    var_2 = maps\mp\gametypes\_hud_util::_id_2829( "default", 2.0 );
    var_2 maps\mp\gametypes\_hud_util::setpoint( "LEFT", "LEFT", var_0, -25 );
    var_2.label = &"MP_SPY_NUM_DETECTIVES";
    var_3 = maps\mp\gametypes\_hud_util::_id_282A( "waypoint_background_shield", var_0, var_0 );
    var_3 maps\mp\gametypes\_hud_util::setpoint( "LEFT", "LEFT", 0, -25 );
    var_4 = maps\mp\gametypes\_hud_util::_id_2829( "default", 2.0 );
    var_4 maps\mp\gametypes\_hud_util::setpoint( "LEFT", "LEFT", var_0, 0 );
    var_4.label = &"MP_SPY_NUM_TRAITORS";
    var_5 = maps\mp\gametypes\_hud_util::_id_282A( "waypoint_faction_axis_icon", var_0, var_0 );
    var_5 maps\mp\gametypes\_hud_util::setpoint( "LEFT", "LEFT", 0, 0 );
    var_6 = [ var_1, var_2, var_4 ];
    var_7 = getaliveclasscounts();

    foreach ( var_10, var_9 in var_6 )
        var_9 setvalue( var_7[var_10] );

    for (;;)
    {
        waitforspyplayerupdate();
        waittillframeend;
        var_11 = getaliveclasscounts();

        foreach ( var_10, var_9 in var_6 )
        {
            var_13 = var_11[var_10] - var_7[var_10];

            if ( var_13 )
            {
                var_9 setvalue( var_11[var_10] );
                var_9 thread onserverhudchange( var_13 );
            }
        }

        var_7 = var_11;
    }
}

onserverhudchange( var_0 )
{
    self endon( "death" );
    self notify( "onServerHudChange" );
    self endon( "onServerHudChange" );

    if ( var_0 < 0 )
        self.color = ( 1, 0, 0 );
    else
        self.color = ( 0, 1, 0 );

    wait 0.75;
    self.color = ( 1, 1, 1 );
}

playerassignspyclass()
{
    self endon( "disconnect" );
    maps\mp\_utility::gameflagwait( "prematch_done" );

    if ( !self.hasspawned )
        self waittill( "spawned_player" );

    var_0 = level.players.size + level._id_596C.size;
    var_1 = [];

    for ( var_2 = 0; var_2 < 3; var_2++ )
    {
        var_3 = level.spy_class_maxs[var_0][var_2] - level.spy_class_counts[var_2];

        for ( var_4 = 0; var_4 < var_3; var_4++ )
            var_1[var_1.size] = var_2;
    }

    self.spyclass = common_scripts\utility::random( var_1 );
    level.spy_class_counts[self.spyclass]++;
    self.spyhudclass = maps\mp\gametypes\_hud_util::createfontstring( "default", 1.5 );
    self.spyhudclass maps\mp\gametypes\_hud_util::setpoint( "CENTER", "CENTER", 0, 0 );
    self.spyhudclass.label = &"MP_SPY_HUD_CLASS";
    self.spyhudclass settext( maps\mp\gametypes\_spy_util::spyclasstolocstring( self.spyclass ) );
    self.spyhudclass maps\mp\gametypes\_hud_util::setpoint( "BOTTOM", "BOTTOM", 0, -10, 2.0 );
    self _meth_82FF( "ui_spy_player_class", self.spyclass );
    playersetheadicon();

    switch ( self.spyclass )
    {
        case 0:
            thread playercivilianthink();
            break;
        case 1:
            thread playerdetectivethink();
            break;
        case 2:
            thread playertraitorthink();
            break;
    }

    level notify( "spyClassSet", self );
}

playercivilianthink()
{
    self endon( "death" );

    for (;;)
    {
        updatelastseenplayer();
        waitframe();
    }
}

playerdetectivethink()
{
    self endon( "death" );

    for (;;)
    {
        updatelastseenplayer();
        waitframe();
    }
}

playertraitorthink()
{
    self endon( "death" );

    for (;;)
        waitframe();
}

playersetheadicon()
{
    if ( self.spyclass == 1 )
        setheadiconspymode( self, "waypoint_background_shield" );
    else if ( self.spyclass == 2 )
        setheadiconspymode( self, "waypoint_faction_axis_icon", [ 2 ] );
}

setheadiconspymode( var_0, var_1, var_2 )
{
    var_3 = spawn( "script_model", var_0.origin );
    var_3 linkto( var_0, "tag_origin" );
    var_3 setmodel( "tag_origin" );
    var_0.spyheadiconent = var_3;
    var_4 = newhudelem();
    var_4.archived = 1;
    var_4.alpha = 1.0;
    var_4 setshader( var_1, 30, 30 );
    var_4 _meth_80CB( 0, 0, 0, 0 );
    var_4.x = 0;
    var_4.y = 0;
    var_4._id_01D9 = 70;
    var_4 _meth_80C0( var_3, "tag_origin" );
    var_0.spyheadicon = var_4;

    if ( isdefined( var_2 ) )
        thread updateheadiconvisible( var_3, var_2 );
}

updateheadiconvisible( var_0, var_1 )
{
    var_0 endon( "death" );
    var_0 _meth_805C();

    for (;;)
    {
        foreach ( var_3 in var_1 )
        {
            foreach ( var_5 in level.players )
            {
                if ( isdefined( var_5.spyclass ) && var_5.spyclass == var_3 )
                    var_0 _meth_8005( var_5 );
            }
        }

        waitforspyplayerupdate();
    }
}

playerremovespyclass()
{
    if ( isdefined( self.spyclass ) )
    {
        level.spy_class_counts[self.spyclass]--;
        self.spyclass = undefined;
    }

    playercleanupspyhud();
    playercleanupheadicon();
}

playercleanupspyhud()
{
    if ( isdefined( self.spyhudclass ) )
        self.spyhudclass destroy();
}

playercleanupheadicon()
{
    if ( isdefined( self.spyheadicon ) )
        self.spyheadicon destroy();

    if ( isdefined( self.spyheadiconent ) )
        self.spyheadiconent delete();
}

_id_6B7B( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    level notify( "player_killed", self );
    playercleanupspyhud();
    spycheckforwin();
    spawntombstone( var_1, self );

    if ( isplayer( var_1 ) && isdefined( var_1.spyclass ) && isdefined( self.spyclass ) )
    {
        if ( maps\mp\gametypes\_spy_util::spyclassfriendlycheck( var_1.spyclass, self.spyclass ) )
        {
            var_1 iprintlnbold( &"MP_FRIENDLY_FIRE_WILL_NOT" );
            var_10 = 1;

            if ( var_10 )
                var_1 maps\mp\_utility::_suicide();
        }
    }
}

_id_6B5C( var_0, var_1, var_2 )
{

}

getaliveclasscounts()
{
    var_0 = 0;
    var_1 = 0;
    var_2 = 0;

    foreach ( var_4 in level.players )
    {
        if ( !maps\mp\_utility::isreallyalive( var_4 ) )
            continue;

        if ( !isdefined( var_4.spyclass ) )
            continue;

        if ( var_4.spyclass == 0 )
        {
            var_0++;
            continue;
        }

        if ( var_4.spyclass == 1 )
        {
            var_1++;
            continue;
        }

        if ( var_4.spyclass == 2 )
            var_2++;
    }

    return [ var_0, var_1, var_2 ];
}

spycheckforwin()
{
    [var_1, var_2, var_3] = getaliveclasscounts();
    var_4 = var_1 + var_2;

    if ( !var_3 && var_4 )
        spy_endgame( 0, game["end_reason"]["axis_eliminated"] );
    else if ( var_3 && !var_4 )
        spy_endgame( 2, game["end_reason"]["allies_eliminated"] );
}

modifyplayerdamagespymode( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    if ( isplayer( var_2 ) && !maps\mp\_utility::gameflag( "spy_loot_done" ) )
    {
        var_2 iprintlnbold( &"MP_SPY_NO_DAMAGE" );
        return 0;
    }

    return var_3;
}

_id_6B7F( var_0, var_1, var_2, var_3, var_4 )
{
    var_5 = maps\mp\gametypes\_rank::getscoreinfovalue( var_0 );
    var_1 maps\mp\_utility::_id_867B( var_1._id_008F + var_5 );
    var_1 _id_04D2::_id_A161( var_1, var_5 );
    return 0;
}

_id_6BA7()
{
    setplayerclass( self );
}

setplayerclass( var_0 )
{
    var_1 = maps\mp\gametypes\_class::_id_44B4();
    var_1["loadoutDivision"] = randomint( 5 );
    var_1["loadoutPrimaryWeaponStruct"] = maps\mp\_utility::_id_473C( 17113088, 0 );
    var_0.pers["class"] = "gamemode";
    var_0.pers["lastClass"] = "";
    var_0.pers["gamemodeLoadout"] = var_1;
    var_0.class = var_0.pers["class"];
    var_0.lastclass = var_0.pers["lastClass"];
    var_0 maps\mp\gametypes\_class::_id_4790( var_0.team, var_0.class );
}

maydropweaponspymode( var_0 )
{
    if ( var_0 == "shovel_mp" )
        return 0;

    maps\mp\gametypes\_spy_loot::lootdropweapon( var_0 );
    return 0;
}

applyspyperks()
{

}

spawntombstone( var_0, var_1 )
{
    var_2 = spawn( "script_model", ( 0, 0, 0 ) );
    var_2 setmodel( "prop_ger_kc_dogtags" );
    var_2.origin = var_1.origin;
    var_2 makeusable();
    var_2 _meth_80CE( &"MP_SPY_INVESTIGATE_CORPSE" );
    var_2 _meth_80CD( "HINT_NOICON" );
    var_2._id_A490 = var_1;
    var_2.victimspyclass = var_1.spyclass;
    var_2.victimlastplayerseen = var_1.lastplayerseen;
    var_2 thread tombstoneupdate();
    var_2 thread tombstoneuse();
}

tombstoneupdate()
{
    self endon( "death" );

    for (;;)
    {
        self _meth_83FF();
        var_0 = [];

        foreach ( var_2 in level.players )
        {
            if ( isdefined( var_2.spyclass ) && var_2.spyclass == 1 )
            {
                var_0[var_0.size] = var_2;
                self enableplayeruse( var_2 );
                continue;
            }

            self disableplayeruse( var_2 );
        }

        if ( var_0.size )
            self _meth_8429( var_0, 0, 1 );

        waitforspyplayerupdate();
    }
}

tombstoneuse()
{
    self endon( "death" );

    for (;;)
    {
        self waittill( "trigger", var_0 );

        if ( self.victimspyclass == 2 )
        {
            var_0 thread detectivetombstonehud( &"MP_SPY_VICTIM_WAS_TRAITOR" );
            continue;
        }

        var_1 = self.victimlastplayerseen;

        if ( !isdefined( var_1 ) )
            var_1 = "unknown";

        var_0 thread detectivetombstonehud( &"MP_SPY_VICTIM_WAS_NOT_TRAITOR", var_1 );
    }
}

detectivetombstonehud( var_0, var_1 )
{
    self notify( "dectiveTombstoneHud" );
    var_2 = maps\mp\gametypes\_hud_util::createfontstring( "default", 1.5 );
    var_2 maps\mp\gametypes\_hud_util::setpoint( "CENTER", "CENTER", 0, 0 );
    var_2.label = var_0;

    if ( isdefined( var_1 ) )
    {
        if ( isplayer( var_1 ) )
            var_2 _meth_8084( var_1 );
        else if ( var_1 == "unknown" )
            var_2 settext( &"MP_SPY_LAST_SEEN_UNKNOWN" );
    }

    common_scripts\utility::waittill_notify_or_timeout( "dectiveTombstoneHud", 4 );

    if ( isdefined( var_2 ) )
        var_2 destroy();
}

updatelastseenplayer()
{
    var_0 = self _meth_82F0();

    if ( !var_0.size )
        return;

    var_0 = sortbydistance( var_0, self.origin );
    self.lastplayerseen = var_0[0];
}

waitforspyplayerupdate()
{
    level common_scripts\utility::_id_A70A( "spyClassSet", "joined_team", "joined_spectators", "player_killed" );
}
